# -*- coding: utf-8 -*-
"""
by Artifact Studio Jewelry · Pinterest seti (2026-09-26), 60 pin.

Tek kaynak: her pinin görsel kurgusu (şablon + kaynak kareler + üstündeki metin)
ve Pinterest alanları (başlık, açıklama, alt metin, link, pano) burada durur.
`render.py` bu listeyi 1000x1500 (2:3) JPG'lere çevirir, `sheet.py` içe aktarma
tablosunu doldurur.

Kaynak kare kodu: `<product_id ilk 8>_<listing_images.position 2 hane>`.
Kural: yüzeye yazılan her iddia listing'in kendisinde olmalı. Taş türü
belirsiz olan üründe (Cercle) "natural" denmez; Cartouche Etsy'de henüz eski
yapıda (US 3 ila 10, 18K beyaz ve rose yok) olduğu için bu ikisi vaat edilmez.
"""

SHOP = "https://www.etsy.com/shop/byArtifactStudio"


def L(listing_id: int) -> str:
    return f"https://www.etsy.com/listing/{listing_id}"


# listing id'leri (products.etsy_listing_id)
CARTOUCHE = L(4582948003)
INITIAL = L(4578893291)
MILGRAIN = L(4576009060)
ARC = L(4578936078)
SUNRISE = L(4579914547)
ROSETTE = L(4579188284)
FLORAL = L(4579931388)
INF_RING = L(4579170829)
FRIEZE = L(4582909101)
CERCLE = L(4581312197)
EYE_RED = L(4575369430)
EYE_BLUE = L(4579034421)
TWIST = L(4576455789)
INF_BLUE = L(4576447677)
SUNRAY = L(4578602443)
RIBBON = L(4574630211)
VPEND = L(4581302864)
LARIAT = L(4581283366)
FRAME = L(4575795744)
INF_NECK = L(4579027067)
LION = L(4579022187)

# Şablonlar:
#  editorial  foto üstte, fildişi bant: etiket + serif başlık + mono alt satır
#  story      fildişi zemin, kare foto, etiket + italik hikâye + alt satır
#  word       tam kadraj foto, alt gölge, tek büyük serif kelime + mono satır
#  diptych    iki foto üst üste, fildişi şerit: etiket + başlık
#  guide      fildişi zemin, serif başlık, kare foto, numaralı liste
#  trio       üç dikey şerit foto, fildişi bant: etiket + başlık
PINS = [
    # ─────────────────────────── RINGS ───────────────────────────
    dict(n=1, board="Rings", t="editorial", img=["e42cd433_00"], focus=[0.5],
         label="N° 01 · PINKY SIGNET", head="The quiet signet, made for the little finger",
         foot="SOLID 10K · 14K · 18K GOLD",
         title="Pinky Signet Ring in Solid Gold, Minimal Oval Face for Initials",
         desc="A quiet oval signet made for the little finger, cast in solid 10K, 14K or 18K gold with a smooth face left blank for your initials. Minimal, heirloom and made to order. Tap to see sizes and colours on Etsy.",
         alt="Minimal solid yellow gold oval pinky signet ring standing on a dark granite plinth",
         link=CARTOUCHE, pr="high"),
    dict(n=2, board="Rings", t="story", img=["e42cd433_01"],
         label="STORY · THE PINKY SIGNET",
         body="For centuries a signet was a signature you wore. Ours keeps the oval face smooth, so the mark you carry is the one you choose: initials, a monogram, or nothing at all.",
         foot="BY ARTIFACT STUDIO",
         title="The Story of the Pinky Signet Ring: a Signature You Wear",
         desc="Signet rings were once worn as a personal seal. Our minimal pinky signet keeps the oval face smooth so you decide what it says: initials, a monogram or nothing at all. Solid gold, made to order. Read more and shop on Etsy.",
         alt="Man's hand resting on dark wool wearing a gold oval signet ring on the little finger",
         link=CARTOUCHE, pr="high"),
    dict(n=3, board="Rings", t="word", img=["e42cd433_03"], focus=[0.5],
         word="Yours.", sub="AN OVAL FACE, LEFT BLANK FOR YOUR INITIALS",
         title="Engravable Gold Signet Ring, Blank Oval Face for Your Monogram",
         desc="Macro of a polished solid gold signet face, smooth and ready for engraving. Add initials or a monogram up to 4 characters, or keep it blank. A minimalist heirloom ring for everyday wear.",
         alt="Close-up of the smooth polished face of a yellow gold oval signet ring",
         link=CARTOUCHE, pr="low"),
    dict(n=4, board="Rings", t="guide", img=["e42cd433_04"],
         head="What to engrave on a pinky signet",
         items=["01  Your own initials", "02  Your partner's initials", "03  A year that matters"],
         foot="UP TO 4 CHARACTERS · BY ARTIFACT STUDIO",
         title="What to Engrave on a Signet Ring: 3 Classic Monogram Ideas",
         desc="Not sure what to put on a signet ring? Start with your initials, a partner's initials or a year that matters. Our oval pinky signet takes up to 4 characters on a smooth solid gold face. Save for later and shop on Etsy.",
         alt="Gold oval signet ring engraved with the initials A R in serif capitals on dark stone",
         link=CARTOUCHE, pr="high"),
    dict(n=5, board="Rings", t="editorial", img=["e42cd433_08"], focus=[0.5],
         label="THREE GOLDS", head="Yellow, white or rose. One quiet shape.",
         foot="PINKY SIGNET · MADE TO ORDER",
         title="Gold Signet Ring in Yellow, White and Rose Gold, Minimalist Pinky Ring",
         desc="The same minimal oval pinky signet in yellow, white and rose gold. Solid gold, made to order, with a smooth face for optional engraving. Which one is yours? Tap to choose on Etsy.",
         alt="Three oval signet rings in yellow, white and rose gold standing on dark granite",
         link=CARTOUCHE, pr="low"),
    dict(n=6, board="Rings", t="guide", img=["e42cd433_14"],
         head="How to find your pinky ring size",
         items=["01  Measure the pinky itself", "02  Between two sizes, go larger", "03  It should slide over the knuckle"],
         foot="SIZING NOTES · BY ARTIFACT STUDIO",
         title="How to Find Your Pinky Ring Size: 3 Tips Before You Order a Signet",
         desc="Pinky ring sizing is different from your ring finger. Measure the little finger itself, choose the larger size if you fall between two, and make sure the ring slides over the knuckle. Save this guide for your next signet ring.",
         alt="A man's and a woman's hands resting together, each wearing a gold signet ring on the little finger",
         link=CARTOUCHE, pr="high"),
    dict(n=7, board="Rings", t="diptych", img=["e42cd433_05", "e42cd433_11"], focus=[0.5, 0.5],
         label="ON THE STONE · ON THE HAND", head="A signet sized for the little finger",
         title="Minimalist Pinky Signet Ring for Men and Women, Solid Gold",
         desc="A minimal oval signet made for the pinky, shown on stone and on the hand. Solid gold in 10K, 14K or 18K with optional initials on the face. A modern heirloom gift for him or her.",
         alt="Gold signet ring on granite above a man's hand wearing it on the little finger beside a leather notebook",
         link=CARTOUCHE, pr="low"),
    dict(n=8, board="Rings", t="word", img=["e42cd433_13"], focus=[0.5],
         word="Heirloom.", sub="A GIFT MEANT TO BE HANDED DOWN",
         title="Heirloom Gold Signet Ring Gift, Engravable Pinky Ring for Christmas",
         desc="A solid gold pinky signet on deep green velvet, a gift meant to be engraved once and handed down. Add initials on the oval face for Christmas, an anniversary or a graduation. Shop on Etsy.",
         alt="Gold oval signet ring on green velvet with warm candlelight behind",
         link=CARTOUCHE, pr="low"),
    dict(n=9, board="Rings", t="editorial", img=["fd02da29_05"], focus=[0.5],
         label="N° 02 · INITIAL SIGNET", head="One letter, set into solid gold",
         foot="14K YELLOW GOLD · A TO Z",
         title="Initial Signet Ring in 14k Solid Gold, Personalized Letter Ring",
         desc="A softly squared 14k yellow gold signet with one recessed uppercase letter of your choice. Minimal, personal and made to order. A thoughtful personalized gift. Tap to choose your letter on Etsy.",
         alt="14k yellow gold signet ring with a recessed capital letter E on travertine",
         link=INITIAL, pr="low"),
    dict(n=10, board="Rings", t="story", img=["fd02da29_00"],
         label="STORY · ONE LETTER",
         body="A single recessed capital on a softly squared face. Up close it reads as a monogram; from across the room it becomes pure form.",
         foot="BY ARTIFACT STUDIO",
         title="The Story Behind Our Initial Signet Ring, One Letter in Gold",
         desc="One recessed letter on a softly squared 14k gold face: personal up close, sculptural from a distance. See how our initial signet ring is designed and choose your letter on Etsy.",
         alt="Hand wearing a gold initial signet ring with the letter E",
         link=INITIAL, pr="high"),
    dict(n=11, board="Rings", t="word", img=["fd02da29_09"], focus=[0.5],
         word="A to Z.", sub="YOUR LETTER, RECESSED INTO 14K GOLD",
         title="Personalized Letter Ring, 14k Gold Initial Signet Gift for Her",
         desc="Choose any letter from A to Z, recessed into a 14k solid yellow gold signet. A minimalist personalized ring and an easy gift for birthdays and holidays.",
         alt="Close-up of a 14k gold signet ring with a recessed letter E",
         link=INITIAL, pr="low"),
    dict(n=12, board="Rings", t="editorial", img=["5ac68aea_00"], focus=[0.5],
         label="N° 03 · MILGRAIN BAND", head="Satin centre, beaded edges, made to last",
         foot="SOLID 14K GOLD WEDDING BAND",
         title="Milgrain Wedding Band in Solid 14K Gold, Satin Finish Beveled Edge",
         desc="A solid 14K gold wedding band with a satin centre, beveled shoulders and fine milgrain beading on both edges. Classic, comfortable and made to order. Tap to see widths and sizes on Etsy.",
         alt="Solid yellow gold milgrain wedding band with satin centre on an ivory background",
         link=MILGRAIN, pr="low"),
    dict(n=13, board="Rings", t="story", img=["5ac68aea_01"],
         label="STORY · THE OLDEST DETAIL",
         body="Milgrain is a row of tiny gold beads pressed along the edge. It catches light the way old family rings do, and softens the line of a modern band.",
         foot="BY ARTIFACT STUDIO",
         title="What Is Milgrain? The Vintage Detail on Our Gold Wedding Band",
         desc="Milgrain means a row of tiny beads along the edge of a ring, a vintage detail that catches light and softens a modern band. See it on our solid 14K gold wedding band and save for your wedding board.",
         alt="Macro of fine milgrain beading along the edge of a satin gold band",
         link=MILGRAIN, pr="high"),
    dict(n=14, board="Rings", t="diptych", img=["5ac68aea_09", "5ac68aea_11"], focus=[0.5, 0.5],
         label="FOR BOTH OF YOU", head="A wedding band for two hands",
         title="His and Hers Gold Wedding Bands, Milgrain Satin Solid 14K",
         desc="A matching milgrain wedding band for both of you, in solid 14K gold with a satin centre and beaded edges. Available in yellow, rose and white gold. Save for your wedding and shop on Etsy.",
         alt="Two hands wearing matching gold wedding bands above a gold band on black stone",
         link=MILGRAIN, pr="low"),
    dict(n=15, board="Rings", t="editorial", img=["5ac68aea_02"], focus=[0.5],
         label="YELLOW · ROSE · WHITE", head="Three golds, one wedding band",
         foot="MILGRAIN · SATIN · 14K",
         title="Milgrain Wedding Band in Yellow, Rose or White Gold, Solid 14K",
         desc="Our satin milgrain wedding band in three golds: yellow, rose and white. Solid 14K, made to order. Which gold suits you best? Tap to compare on Etsy.",
         alt="Three milgrain wedding bands in yellow, rose and white gold side by side",
         link=MILGRAIN, pr="low"),
    dict(n=16, board="Rings", t="editorial", img=["3d93ca29_00"], focus=[0.5],
         label="N° 04 · OPEN ARC RING", head="Two peaks and a fine open arc",
         foot="14K GOLD · THREE COLOURS",
         title="Sculptural Gold Ring, Open Arc Stacking Ring in 14K Gold",
         desc="Two softly rising peaks joined by a fine open arc, in polished 14K gold. A sculptural stacking ring that feels light on the hand. Available in yellow, white and rose gold on Etsy.",
         alt="Yellow gold open arc ring with two peaks on an ivory background",
         link=ARC, pr="low"),
    dict(n=17, board="Rings", t="guide", img=["3d93ca29_03"],
         head="How to stack a sculptural ring",
         items=["01  Pair it with a plain band", "02  Mix yellow and rose gold", "03  Leave one finger bare"],
         foot="STACKING NOTES · BY ARTIFACT STUDIO",
         title="How to Stack Gold Rings: 3 Simple Rules for a Minimal Ring Stack",
         desc="Stacking rings without the clutter: pair one sculptural ring with a plain band, mix yellow and rose gold, and leave one finger bare. Shown with our 14K open arc ring. Save for your next stack.",
         alt="Hand wearing a gold open arc ring with two peaks",
         link=ARC, pr="high"),
    dict(n=18, board="Rings", t="trio", img=["3d93ca29_06", "3d93ca29_07", "3d93ca29_08"], focus=[0.5, 0.5, 0.5],
         label="YELLOW · WHITE · ROSE", head="The same arc in three golds",
         title="Open Arc Ring in Yellow, White and Rose Gold, Minimalist 14K",
         desc="One sculptural open arc ring, three golds. Solid 14K in yellow, white or rose, made to order. Tap to pick your colour on Etsy.",
         alt="Open arc gold ring shown in yellow, white and rose gold",
         link=ARC, pr="low"),
    dict(n=19, board="Rings", t="story", img=["2b6a52b9_00"],
         label="STORY · THE SUNRISE RING",
         body="Two mountain peaks and a small sun rising between them. We made it for beginnings: a new city, a new job, a first morning somewhere far from home.",
         foot="BY ARTIFACT STUDIO",
         title="Sunrise Ring Meaning: a Gold Mountain Ring for New Beginnings",
         desc="Two mountain peaks with a small sun rising between them, in 14k solid yellow gold. A meaningful gift for a new chapter: a move, a new job, a graduation. Discover the sunrise ring on Etsy.",
         alt="14k gold ring with two mountain peaks and a raised sun",
         link=SUNRISE, pr="high"),
    dict(n=20, board="Rings", t="story", img=["276666a7_00"],
         label="STORY · THE ROSETTE",
         body="Five open petals around a round centre, one petal gently clipped as if the flower is still growing. Small enough to stack, clear enough to notice.",
         foot="BY ARTIFACT STUDIO",
         title="Rosette Ring in 14k Gold, a Delicate Flower Stacking Ring",
         desc="Five open petals around a round centre, one gently clipped as if still growing. A delicate 14k solid gold flower ring that stacks easily. Shop the rosette ring on Etsy.",
         alt="Delicate 14k gold ring with an open five petal flower",
         link=ROSETTE, pr="high"),
    dict(n=21, board="Rings", t="editorial", img=["e250e7b1_00"], focus=[0.5],
         label="N° 05 · FIVE PETAL RING", head="A small gold flower for every day",
         foot="14K SOLID YELLOW GOLD",
         title="Gold Flower Ring, 14K Solid Five Petal Floral Band",
         desc="Five rounded gold petals with a recessed centre on a slim polished band. A 14K solid gold floral ring for everyday wear and a sweet gift for her. Tap to shop on Etsy.",
         alt="14k yellow gold ring with a five petal flower",
         link=FLORAL, pr="low"),
    dict(n=22, board="Rings", t="editorial", img=["8ba6735d_00"], focus=[0.5],
         label="OPEN INFINITY RING", head="Always, drawn in one open line",
         foot="14K SOLID YELLOW GOLD",
         title="Infinity Ring in 14k Solid Gold, Open Symbol Stacking Band",
         desc="An asymmetrical open infinity in 14k solid yellow gold on a slim stacking band. A quiet everyday symbol and a meaningful gift. Shop on Etsy.",
         alt="14k yellow gold infinity ring on an ivory background",
         link=INF_RING, pr="low"),
    # ───────────────────────── BRACELETS ─────────────────────────
    dict(n=23, board="Bracelets", t="editorial", img=["43bdaf32_00"], focus=[0.5],
         label="N° 06 · REEDED CUFF", head="Fine grooves, open cuff, solid gold",
         foot="10K · 14K · 18K GOLD",
         title="Solid Gold Cuff Bracelet, Reeded Open Bangle in 10K 14K 18K",
         desc="A solid gold open cuff with fine parallel grooves on the outside and a smooth interior for optional hidden engraving. Available in 10K, 14K or 18K gold. Tap to shop on Etsy.",
         alt="Yellow gold reeded open cuff bracelet standing on a pale stone plinth",
         link=FRIEZE, pr="low"),
    dict(n=24, board="Bracelets", t="story", img=["43bdaf32_02"],
         label="STORY · THE HIDDEN LINE",
         body="The outside is all rhythm, fine parallel grooves. The inside stays smooth for a few words only the wearer knows.",
         foot="INSIDE ENGRAVING UP TO 10 CHARACTERS",
         title="Hidden Message Gold Cuff: Engrave a Secret Word Inside",
         desc="Our reeded gold cuff keeps its inside smooth for a hidden message only the wearer knows. Add up to 10 characters: a date, a name, a word. Solid gold, made to order. Discover it on Etsy.",
         alt="Gold cuff tilted to show the word EVER engraved on the smooth inside",
         link=FRIEZE, pr="high"),
    dict(n=25, board="Bracelets", t="word", img=["43bdaf32_01"], focus=[0.5],
         word="Reeded.", sub="PARALLEL GROOVES, EDGE TO EDGE",
         title="Reeded Gold Cuff Bracelet Close Up, Textured Solid Gold Bangle",
         desc="Fine parallel grooves run edge to edge across this solid gold cuff, catching light with every move. A modern textured bangle in 10K, 14K or 18K. Shop on Etsy.",
         alt="Macro of fine parallel grooves on a gold cuff bracelet",
         link=FRIEZE, pr="low"),
    dict(n=26, board="Bracelets", t="guide", img=["43bdaf32_06"],
         head="Six things to engrave inside a cuff",
         items=["01  A date", "02  A name", "03  Coordinates", "04  One word", "05  Initials", "06  A year"],
         foot="UP TO 10 CHARACTERS · BY ARTIFACT STUDIO",
         title="What to Engrave Inside a Bracelet: 6 Hidden Message Ideas",
         desc="Stuck on what to engrave? A date, a name, coordinates, one word, initials or a year all fit inside our reeded gold cuff (up to 10 characters). Save these ideas for your next personalized gift.",
         alt="Wrist wearing a gold cuff resting beside a ceramic coffee cup",
         link=FRIEZE, pr="high"),
    dict(n=27, board="Bracelets", t="editorial", img=["43bdaf32_08"], focus=[0.5],
         label="THREE GOLDS", head="Pick your gold, keep the grooves",
         foot="REEDED CUFF · MADE TO ORDER",
         title="Gold Cuff Bracelet in Yellow, White and Rose Gold, Reeded Bangle",
         desc="The reeded open cuff in yellow, white and rose gold. Solid gold, made to order, with optional hidden engraving inside. Which gold is yours? Tap to choose on Etsy.",
         alt="Three reeded cuffs in yellow, white and rose gold on a stone plinth",
         link=FRIEZE, pr="low"),
    dict(n=28, board="Bracelets", t="diptych", img=["43bdaf32_11", "43bdaf32_13"], focus=[0.5, 0.5],
         label="STACKED · GIFTED", head="Wear two, or wrap one",
         title="Stacked Gold Cuffs and Holiday Gift Idea, Solid Gold Bangle",
         desc="Stack two reeded cuffs on one wrist or wrap one as a holiday gift. Solid gold open bangle with optional hidden engraving. Save for your gift list and shop on Etsy.",
         alt="Wrist with two stacked gold cuffs above a gold cuff on green velvet",
         link=FRIEZE, pr="low"),
    dict(n=29, board="Bracelets", t="editorial", img=["bec09989_01"], focus=[0.5],
         label="N° 07 · OPEN CIRCLE", head="A circle of diamonds on a fine chain",
         foot="14K SOLID YELLOW GOLD",
         title="Diamond Circle Bracelet in 14k Solid Gold, Dainty Pave Open Circle",
         desc="An open circle set with small pavé diamonds and a bezel-set diamond beside it, on a fine 14k solid gold cable chain. Dainty, sparkling and made to order. Tap to shop on Etsy.",
         alt="14k gold bracelet with a pave diamond open circle and a bezel-set stone",
         link=CERCLE, pr="low"),
    dict(n=30, board="Bracelets", t="story", img=["bec09989_02"],
         label="STORY · THE CIRCLE",
         body="An open circle has no start and no end. Ours is set all the way round with small pavé diamonds, with one bezel-set stone waiting beside it.",
         foot="BY ARTIFACT STUDIO",
         title="The Meaning of a Circle Bracelet: No Start and No End",
         desc="A circle has no beginning and no end, which is why it makes such a meaningful gift. Our 14k gold open circle bracelet is set with pavé diamonds and one bezel-set stone. Discover it on Etsy.",
         alt="Wrist wearing a gold bracelet with a diamond open circle",
         link=CERCLE, pr="high"),
    dict(n=31, board="Bracelets", t="word", img=["bec09989_04"], focus=[0.5],
         word="Glow.", sub="PAVÉ DIAMONDS IN 14K YELLOW GOLD",
         title="Sparkly Diamond Bracelet for Evening, 14k Gold Circle Bracelet",
         desc="Pavé diamonds catching candlelight on a 14k solid gold open circle bracelet. A dainty piece for evenings and holidays. Shop the circle bracelet on Etsy.",
         alt="Close-up of a pave diamond circle bracelet in warm candlelight",
         link=CERCLE, pr="low"),
    dict(n=32, board="Bracelets", t="editorial", img=["9482af28_01"], focus=[0.5],
         label="N° 08 · EVIL EYE · RED STONE", head="A small eye that keeps watch",
         foot="14K SOLID YELLOW GOLD",
         title="Evil Eye Bracelet in 14k Solid Gold with Red Stone, Dainty Chain",
         desc="A polished 14k gold evil eye with a bezel-set red stone on a fine cable chain. A dainty protection bracelet for everyday wear and a meaningful gift. Tap to shop on Etsy.",
         alt="Close-up of a 14k gold evil eye charm with a red stone on a cable chain",
         link=EYE_RED, pr="low"),
    dict(n=33, board="Bracelets", t="story", img=["9482af28_03"],
         label="STORY · THE EVIL EYE",
         body="Across the Mediterranean the eye is worn to turn away bad luck. We kept the old symbol and drew it clean: a polished contour, one stone at its centre.",
         foot="BY ARTIFACT STUDIO",
         title="Evil Eye Meaning: Why We Wear the Eye in Solid Gold",
         desc="Across the Mediterranean the evil eye is worn to turn away bad luck. Our version keeps the old symbol clean and modern, in 14k solid gold with a bezel-set stone. Read the story and shop on Etsy.",
         alt="Fingertip holding a gold evil eye bracelet with a red stone",
         link=EYE_RED, pr="high"),
    dict(n=34, board="Bracelets", t="diptych", img=["3a4a4d97_02", "9482af28_05"], focus=[0.5, 0.5],
         label="BLUE STONE · RED STONE", head="Choose your eye",
         title="Evil Eye Bracelet Blue or Red Stone, 14k Solid Gold",
         desc="Two versions of our 14k solid gold evil eye bracelet: one with a dark blue stone, one with a red stone. Which one would you wear? Save and shop on Etsy.",
         alt="Gold evil eye with a blue stone above a gold evil eye with a red stone",
         link=EYE_BLUE, pr="low"),
    dict(n=35, board="Bracelets", t="guide", img=["3a4a4d97_03"],
         head="Three ways to wear an evil eye bracelet",
         items=["01  Alone, as a quiet charm", "02  Stacked with a plain chain", "03  Given for a new start"],
         foot="STYLE NOTES · BY ARTIFACT STUDIO",
         title="How to Wear an Evil Eye Bracelet: 3 Easy Styling Ideas",
         desc="Wear it alone as a quiet charm, stack it with a plain gold chain, or give it for a new start: a new home, a new job, a new baby. Shown with our 14k gold evil eye bracelet. Save for later.",
         alt="Wrist in a cream sweater wearing a dainty gold evil eye bracelet",
         link=EYE_BLUE, pr="high"),
    dict(n=36, board="Bracelets", t="editorial", img=["3a4a4d97_07"], focus=[0.5],
         label="N° 09 · EVIL EYE · BLUE STONE", head="Solid gold protection, worn every day",
         foot="14K SOLID YELLOW GOLD",
         title="Blue Evil Eye Bracelet, 14k Solid Gold Protection Bracelet",
         desc="An open 14k gold eye contour with a small dark blue stone at its centre, on a fine cable chain. Dainty enough to wear every day. Tap to shop on Etsy.",
         alt="Wrist wearing a 14k gold evil eye bracelet with a blue stone",
         link=EYE_BLUE, pr="low"),
    dict(n=37, board="Bracelets", t="editorial", img=["88d2f627_01"], focus=[0.5],
         label="N° 10 · OPEN TWIST", head="Two unequal paths that meet again",
         foot="14K SOLID YELLOW GOLD",
         title="Infinity Bracelet in 14k Solid Gold, Open Twist Dainty Chain",
         desc="An open twist infinity motif with two unequal paths on a fine 14k solid gold cable chain. Polished, light and made to order. Tap to shop on Etsy.",
         alt="Close-up of a 14k gold open twist infinity charm on a cable chain",
         link=TWIST, pr="low"),
    dict(n=38, board="Bracelets", t="story", img=["88d2f627_03"],
         label="STORY · THE OPEN TWIST",
         body="Most infinity symbols are perfectly balanced. This one is not: one path is wider than the other, like two people who keep finding their way back.",
         foot="BY ARTIFACT STUDIO",
         title="An Infinity Bracelet With a Story: Two Paths That Meet Again",
         desc="Our open twist infinity is drawn with two unequal paths, like two people who keep finding their way back to each other. 14k solid gold on a fine chain. A meaningful gift for a partner or best friend.",
         alt="Wrist wearing a gold open twist infinity bracelet",
         link=TWIST, pr="high"),
    dict(n=39, board="Bracelets", t="editorial", img=["39179a70_00"], focus=[0.5],
         label="N° 11 · INFINITY · BLUE ACCENT", head="One blue note in a golden loop",
         foot="14K SOLID YELLOW GOLD",
         title="Infinity Bracelet with Blue Stone, 14k Solid Gold Dainty Chain",
         desc="A polished open infinity loop in 14k solid gold with one recessed blue accent, on a fine cable chain. Dainty everyday jewelry and a sweet gift for her. Tap to shop on Etsy.",
         alt="14k gold infinity charm with a small blue stone on a cable chain",
         link=INF_BLUE, pr="low"),
    dict(n=40, board="Bracelets", t="diptych", img=["39179a70_14", "39179a70_10"], focus=[0.5, 0.5],
         label="WORN · WRAPPED", head="From the wrist to the gift box",
         title="Dainty Gold Infinity Bracelet Gift for Her, 14k Solid Gold",
         desc="Worn on the wrist or wrapped in a gift box: our 14k gold infinity bracelet with a blue accent makes an easy, meaningful gift. Save for your gift list and shop on Etsy.",
         alt="Wrist in a knit sleeve wearing a gold infinity bracelet above the bracelet in a gift box",
         link=INF_BLUE, pr="low"),
    dict(n=41, board="Bracelets", t="editorial", img=["86661b37_02"], focus=[0.5],
         label="N° 12 · SUNRAY ARC", head="Morning light on a fine gold chain",
         foot="14K SOLID YELLOW GOLD",
         title="Sunray Bracelet in 14K Solid Gold, Dainty Sun Arc Chain",
         desc="A sculptural sunray arc on a fine 14K solid gold cable chain, with a lobster clasp and adjustment rings. Warm, minimal and made to order. Tap to shop on Etsy.",
         alt="14k gold sunray arc bracelet on travertine in soft light",
         link=SUNRAY, pr="low"),
    dict(n=42, board="Bracelets", t="editorial", img=["86661b37_07"], focus=[0.5],
         label="SUNRAY ARC · ON THE WRIST", head="Close to the wrist, warm as morning",
         foot="14K SOLID YELLOW GOLD",
         title="Dainty Sun Bracelet in 14K Gold, Minimal Everyday Bracelet",
         desc="A small sunray arc that sits close to the wrist, in 14K solid yellow gold. Minimal everyday jewelry with a warm, sunny story. Shop on Etsy.",
         alt="Wrist wearing a dainty gold sunray bracelet",
         link=SUNRAY, pr="low"),
    # ───────────────────────── NECKLACES ─────────────────────────
    dict(n=43, board="Necklaces", t="editorial", img=["891ee44e_00"], focus=[0.5],
         label="N° 13 · RIBBON PENDANT", head="One half turn of solid gold",
         foot="SOLID 14K GOLD · 1.1 MM CHAIN",
         title="Twisted Gold Pendant Necklace in Solid 14K, Ribbon Design",
         desc="A continuous ribbon pendant with one half turn and an open lens-shaped centre, on a matching 14K solid gold cable chain. Sculptural, minimal and made to order. Tap to shop on Etsy.",
         alt="Solid 14k gold twisted ribbon pendant on a fine chain",
         link=RIBBON, pr="low"),
    dict(n=44, board="Necklaces", t="story", img=["891ee44e_01"],
         label="STORY · THE HALF TURN",
         body="A ribbon of gold that turns once and opens into a lens of light. Nothing is added; the shape is the whole design.",
         foot="BY ARTIFACT STUDIO",
         title="The Story of Our Twisted Ribbon Necklace, One Turn of Gold",
         desc="A single ribbon of solid 14K gold turns once and opens into a lens of light. Nothing added, the shape is the design. Discover the ribbon pendant necklace on Etsy.",
         alt="Woman wearing a small twisted gold ribbon pendant",
         link=RIBBON, pr="high"),
    dict(n=45, board="Necklaces", t="trio", img=["891ee44e_09", "891ee44e_10", "891ee44e_11"], focus=[0.5, 0.5, 0.5],
         label="YELLOW · WHITE · ROSE", head="The ribbon in three golds",
         title="Twisted Pendant Necklace in Yellow, White and Rose Gold",
         desc="Our twisted ribbon pendant in yellow, white and rose gold, solid 14K with a fine cable chain. Which gold is yours? Tap to choose on Etsy.",
         alt="Twisted ribbon pendants in yellow, white and rose gold",
         link=RIBBON, pr="low"),
    dict(n=46, board="Necklaces", t="word", img=["891ee44e_13"], focus=[0.5],
         word="Turn.", sub="A CONTINUOUS RIBBON PENDANT IN 14K",
         title="Minimalist Gold Pendant Necklace, Sculptural Twist in 14K",
         desc="A sculptural twisted gold pendant against a dark background. Solid 14K gold, made to order. A modern minimalist necklace for everyday and evening. Shop on Etsy.",
         alt="Twisted gold ribbon pendant against a dark background",
         link=RIBBON, pr="low"),
    dict(n=47, board="Necklaces", t="editorial", img=["f8fd6aa6_00"], focus=[0.5],
         label="N° 14 · V PENDANT", head="A point of light at the collarbone",
         foot="14K GOLD · LAB-GROWN DIAMOND",
         title="V Necklace in 14k Gold with Square Lab-Grown Diamond, 18 Inch",
         desc="A clean open V pendant in 14k yellow gold with one square-cut lab-grown diamond set at the point, on an 18-inch fine chain. Minimal and elegant. Tap to shop on Etsy.",
         alt="14k gold V pendant necklace with a square lab-grown diamond",
         link=VPEND, pr="low"),
    dict(n=48, board="Necklaces", t="story", img=["f8fd6aa6_02"],
         label="STORY · THE V",
         body="A clean open V that follows the neckline, with one square-cut lab-grown diamond set exactly at the point, where the eye lands first.",
         foot="BY ARTIFACT STUDIO",
         title="Why a V Necklace Flatters Every Neckline, 14k Gold Diamond Pendant",
         desc="A V pendant follows the line of the neck and draws the eye to one point. Ours sets a square-cut lab-grown diamond exactly there, in 14k yellow gold. Read the story and shop on Etsy.",
         alt="Woman in a white V neck wearing a gold V pendant necklace",
         link=VPEND, pr="high"),
    dict(n=49, board="Necklaces", t="word", img=["f8fd6aa6_05"], focus=[0.5],
         word="Point.", sub="SQUARE-CUT LAB-GROWN DIAMOND · 14K",
         title="Holiday Gift Necklace, 14k Gold V Pendant with Lab Diamond",
         desc="A 14k gold V pendant with a square-cut lab-grown diamond on deep green velvet. A minimal, meaningful holiday gift for her. Shop on Etsy.",
         alt="Gold V pendant necklace laid on green velvet",
         link=VPEND, pr="low"),
    dict(n=50, board="Necklaces", t="editorial", img=["3dae80ba_00"], focus=[0.5],
         label="N° 15 · STAR LARIAT", head="A four-point star and a fine drop",
         foot="14K YELLOW GOLD",
         title="Star Lariat Necklace in 14K Gold, Dainty Y Drop Necklace",
         desc="A four-point star at the Y junction and a matching star at the end of a fine drop, in 14K yellow gold. A dainty lariat that sits close to the body. Tap to shop on Etsy.",
         alt="14k gold Y lariat necklace with a four point star",
         link=LARIAT, pr="low"),
    dict(n=51, board="Necklaces", t="story", img=["3dae80ba_03"],
         label="STORY · THE NORTH STAR",
         body="Sailors used one fixed star to find their way home. We placed a small four-point star at the Y of this lariat, and another at the very end of the drop.",
         foot="BY ARTIFACT STUDIO",
         title="North Star Necklace Meaning: a Gold Lariat to Find Your Way",
         desc="Sailors navigated by one fixed star. Our 14K gold star lariat carries a four-point star at the Y and another at the end of the drop, a small reminder of the way home. A meaningful gift. Shop on Etsy.",
         alt="Woman in a white top wearing a dainty gold star lariat necklace",
         link=LARIAT, pr="high"),
    dict(n=52, board="Necklaces", t="diptych", img=["3dae80ba_04", "3dae80ba_07"], focus=[0.5, 0.5],
         label="GIFTED · WORN", head="A small star for a long season",
         title="Star Necklace Gift Idea, Dainty 14K Gold Lariat for Christmas",
         desc="Our 14K gold star lariat in a gift box and on a winter morning table. An easy, meaningful Christmas gift for her. Save for your gift list and shop on Etsy.",
         alt="Gold star lariat necklace in a gift box above the necklace beside a coffee cup",
         link=LARIAT, pr="low"),
    dict(n=53, board="Necklaces", t="editorial", img=["7cc5e038_00"], focus=[0.5],
         label="N° 16 · OPEN FRAME", head="A window of gold with one red stone",
         foot="SOLID 14K YELLOW GOLD",
         title="Geometric Gold Necklace with Red Stone, Solid 14K Open Frame",
         desc="A polished open rectangle in solid 14K yellow gold with a red stone set flush into one corner. A modern geometric pendant necklace. Tap to shop on Etsy.",
         alt="Solid 14k gold open rectangle pendant with a flush-set red stone",
         link=FRAME, pr="low"),
    dict(n=54, board="Necklaces", t="story", img=["7cc5e038_02"],
         label="STORY · THE FRAME",
         body="An open rectangle of polished gold with a red stone set flush into one corner. Look through it and the pendant becomes whatever sits behind it.",
         foot="BY ARTIFACT STUDIO",
         title="A Gold Frame Necklace That Changes With You, Red Stone Pendant",
         desc="An open frame pendant shows whatever sits behind it, your skin, your shirt, the light. One red stone sits flush in the corner. Solid 14K gold. Read the story and shop on Etsy.",
         alt="Woman wearing a gold open rectangle pendant with a red stone",
         link=FRAME, pr="high"),
    dict(n=55, board="Necklaces", t="editorial", img=["91250e1d_00"], focus=[0.5],
         label="N° 17 · INFINITY NECKLACE", head="A wide infinity on a fine cable chain",
         foot="14K SOLID YELLOW GOLD",
         title="Infinity Necklace in 14k Solid Gold, Wide Symbol Dainty Chain",
         desc="A polished wide infinity symbol in 14k solid yellow gold on a fine cable chain. A classic meaningful necklace for everyday wear. Tap to shop on Etsy.",
         alt="14k gold wide infinity necklace on a fine chain",
         link=INF_NECK, pr="low"),
    dict(n=56, board="Necklaces", t="story", img=["4f8f6b84_00"],
         label="STORY · THE LION",
         body="Courage, drawn in one open line. The mane flows into the profile without a break, so the lion reads at a glance and never feels heavy.",
         foot="BY ARTIFACT STUDIO",
         title="Lion Pendant Meaning: Courage in 14k Solid Gold",
         desc="The lion has stood for courage for thousands of years. Our 14k solid gold lion pendant draws it in one open line, light enough for every day. A meaningful gift for a Leo or anyone starting something brave.",
         alt="14k gold open line lion profile pendant on a cable chain",
         link=LION, pr="high"),
    # ─────────────────────── STUDO JEWELRY ───────────────────────
    dict(n=57, board="Studo Jewelry", t="guide", img=["43bdaf32_03"],
         head="Why we only work in solid gold",
         items=["01  No plating to wear through", "02  Resized and polished for decades", "03  Keeps its value as metal"],
         foot="BY ARTIFACT STUDIO",
         title="Solid Gold vs Gold Plated Jewelry: Why We Only Use Solid Gold",
         desc="Plated jewelry wears through; solid gold does not. It can be resized and polished for decades and keeps its value as metal. That is why every piece at Artifact Studio is solid 10K, 14K or 18K gold. Save this guide.",
         alt="Yellow gold reeded cuff bracelet on an ivory background",
         link=SHOP, pr="high"),
    dict(n=58, board="Studo Jewelry", t="guide", img=["5ac68aea_08"],
         head="10K, 14K or 18K: which gold is right for you?",
         items=["01  10K · the most durable", "02  14K · the everyday balance", "03  18K · the richest colour"],
         foot="GOLD NOTES · BY ARTIFACT STUDIO",
         title="10K vs 14K vs 18K Gold: How to Choose the Right Gold Jewelry",
         desc="10K is the most durable, 14K balances colour and strength for everyday wear, and 18K has the richest colour but is softer. A quick guide to choosing your gold before you order. Save for later.",
         alt="Macro of a satin finish solid gold band with milgrain edges",
         link=SHOP, pr="high"),
    dict(n=59, board="Studo Jewelry", t="diptych", img=["7cc5e038_09", "bec09989_09"], focus=[0.5, 0.5],
         label="MADE TO ORDER", head="Made for you, not for a shelf",
         title="Made to Order Solid Gold Jewelry by Artifact Studio",
         desc="Every piece at Artifact Studio is made to order in solid gold, then packed in a simple gift box. Minimal designs with a story behind each one. Explore the shop on Etsy.",
         alt="Gold pendant on dark stone above a gold bracelet in an ivory gift box",
         link=SHOP, pr="low"),
    dict(n=60, board="Studo Jewelry", t="trio", img=["3d93ca29_00", "fd02da29_05", "e42cd433_00"], focus=[0.5, 0.5, 0.5],
         label="THREE RINGS · THREE STORIES", head="Minimal gold, each with a reason",
         title="Minimalist Solid Gold Rings With a Story, Artifact Studio",
         desc="An open arc ring, an initial signet and a pinky signet: three minimal solid gold rings, each designed with a reason. Explore the stories and the full collection on Etsy.",
         alt="Three gold rings: an open arc ring, an initial signet and an oval pinky signet",
         link=SHOP, pr="low"),
]

assert len(PINS) == 60 and [p["n"] for p in PINS] == list(range(1, 61))
