# -*- coding: utf-8 -*-
"""
by Artifact Studio Jewelry · FW 26/27 enamel · Pinterest seti (2026-09-30), 80 pin.

Tek kaynak: her pinin görsel kurgusu (şablon + kaynak kareler + üstündeki metin)
ve Pinterest alanları (başlık, açıklama, alt metin, link, pano). `render.py`
1000x1500 (2:3) JPG üretir, `sheet.py` içe aktarma tablosunu doldurur.

Kaynak kod: `R01` = hero (public/artifact/fw2627-enamel/R01.jpg), `R01/04` =
galeri karesi. Kareler: 02 takılı, 03 yaşam, 04 makro, 05 ölçek, 06 profil,
07 natürmort, 08 hediye, 09 üç metal (renk görselleştirmesi), 10 aile.

Yapı: 10 aile × 8 pin. Her ailede bir hikâye pini ve bir rehber pini (ikisi de
priority=high), bir aile karesi (quad) ve ürün pinleri. `link` bir katalog id'si
(R01…) ya da "SHOP"; sheet.py id'yi Etsy listing adresine çevirir.

Kural: yüzeye yazılan her ürün iddiası listing'in kendi metninde olmalı
(ölçü, zincir, kapama, bakım). Rehber pinlerindeki genel bilgi (boy seçimi,
ölçü alma) ürün vaadi değildir, takı bilgisidir. "Natural", taş, "waterproof"
gibi listing'de olmayan iddia yok. 09 karesi renk görselleştirmesidir; pin
"shown in yellow, white and rose gold" der, fotoğraf demez.
"""

SHOP = "SHOP"
KILN = "SOLID GOLD · KILN-FIRED ENAMEL"


def fam(ids):
    return [f"{k}{ids}" for k in "RNEB"]


PINS = [
    # ─────────────── 01 KEYHOLE · Transformative Teal ───────────────
    dict(n=1, board="Rings", t="editorial", img=["R01"], label="N° 01 · KEYHOLE SIGNET",
         head="A small door, drawn in gold on teal", foot="SOLID 10K · 14K · 18K GOLD",
         title="Keyhole Signet Ring in Solid Gold with Teal Enamel, Minimalist Fall Ring",
         desc="A small rounded signet with a polished gold keyhole traced across flush Transformative Teal enamel. It sits flat and low, so it is easy to wear every day and easy to stack. Solid 10K, 14K or 18K gold in yellow, white or rose, made to order. Tap to see it on Etsy.",
         alt="Solid gold signet ring with a teal enamel top and a polished gold keyhole outline",
         link="R01", pr="low"),
    dict(n=2, board="Necklaces", t="story", img=["N01/03"], label="STORY · THE KEYHOLE",
         body="A keyhole is the quiet door of a winter room. We traced it in polished gold and filled it with teal glass, so one small shape carries a whole season.",
         foot="KEYHOLE FAMILY · FW 26/27",
         title="The Story Behind Our Keyhole Jewelry: a Winter Door in Teal and Gold",
         desc="Why a keyhole? It is the quiet door of a winter room. Our Keyhole family traces that shape in polished gold and fills it with teal glass fused to solid gold. Four pieces, one colour story: a signet, a pendant, studs and a station bracelet. Read the story and save it for your fall wishlist.",
         alt="Woman in an oatmeal wool sweater wearing a small teal enamel keyhole pendant on a gold chain",
         link="N01", pr="high"),
    dict(n=3, board="Necklaces", t="guide", img=["N01/02"], head="Which necklace length is right for you?",
         items=["01  16 in · at the collarbone", "02  18 in · just below it", "03  20 in · made for layering"],
         foot="CHAIN NOTES · ARTIFACT STUDIO",
         title="Necklace Length Guide: 16, 18 or 20 Inch Chain, Which One to Choose",
         desc="Not sure which chain length to order? A 16 inch chain sits at the collarbone, 18 inch falls just below it and is the easiest everyday length, and 20 inch leaves room to layer under a shorter chain. Our enamel pendants come on a 1.2 mm solid gold cable chain in all three lengths. Save this guide.",
         alt="Close crop of a teal enamel keyhole pendant resting just below the collarbone on a fine gold chain",
         link="N01", pr="high"),
    dict(n=4, board="Studo Jewelry", t="word", img=["E01/02"], word="Teal.",
         sub="TWO SMALL KEYHOLES FOR THE LOBE",
         title="Teal Enamel Keyhole Stud Earrings in Solid Gold, Tiny Second Hole Studs",
         desc="Two little keyhole silhouettes in teal glass: colour from across the room, a shape up close. 4 x 6 mm, solid gold posts with screw backs, sold as a pair. Good for a first or second hole. Tap to shop on Etsy.",
         alt="Tiny teal enamel keyhole stud earring worn on an earlobe with hair tucked behind the ear",
         link="E01", pr="low"),
    dict(n=5, board="Bracelets", t="editorial", img=["B01/02"], label="THREE STATIONS",
         head="Three keyholes that catch the light in turn", foot="1.1 MM CABLE CHAIN · 6.5 TO 7.5 IN",
         title="Keyhole Station Bracelet, Dainty Teal Enamel Charm Bracelet in Solid Gold",
         desc="Three flat teal keyholes spaced around a fine 1.1 mm solid gold cable chain. They catch the light one at a time as you move, and the flat stations slide under a cuff and stack with a watch. Choose 6.5, 7 or 7.5 inches. Shop on Etsy.",
         alt="Fine gold chain bracelet with three small teal enamel keyhole stations worn on a wrist",
         link="B01", pr="low"),
    dict(n=6, board="Studo Jewelry", t="quad", img=fam("01"), label="THE KEYHOLE FAMILY",
         head="Four pieces, one teal door",
         title="Teal Enamel Jewelry Set: Keyhole Ring, Necklace, Earrings and Bracelet",
         desc="The Keyhole family from our FW 26/27 enamel collection: a signet ring, a pendant necklace, stud earrings and a station bracelet, all in teal enamel and solid gold. They coordinate without copying each other. Wear one or build the set. Explore on Etsy.",
         alt="Four teal enamel keyhole pieces in gold: a signet ring, a pendant, stud earrings and a chain bracelet",
         link=SHOP, pr="low"),
    dict(n=7, board="Rings", t="editorial", img=["R01/09"], label="THREE GOLDS · ONE TEAL",
         head="Yellow, white or rose around the same keyhole", foot="KEYHOLE SIGNET · MADE TO ORDER",
         title="Enamel Signet Ring in Yellow, White or Rose Gold, Teal Keyhole Design",
         desc="The same teal keyhole signet shown in yellow, white and rose gold. Warm yellow makes the teal richer, white gold makes it cooler, rose softens it. Pick your gold in 10K, 14K or 18K. Which one would you wear? Tap to choose on Etsy.",
         alt="Three keyhole signet rings in yellow, white and rose gold with identical teal enamel tops",
         link="R01", pr="low"),
    dict(n=8, board="Necklaces", t="diptych", img=["N01/08", "N01/07"], focus=[0.5, 0.5],
         label="WRAPPED FOR WINTER", head="A keyhole to give this season",
         title="Teal Keyhole Necklace Gift, Solid Gold Enamel Pendant for Her",
         desc="A small teal keyhole pendant in solid gold, ready to give. Add a gift message at checkout and it ships with the piece, free within the United States. A thoughtful winter gift for someone who loves colour. Shop on Etsy.",
         alt="Teal enamel keyhole pendant in a linen lined gift box above the same pendant in a ceramic dish",
         link="N01", pr="low"),

    # ─────────────── 02 DOMINO · ink black + Wax Paper cream ───────────────
    dict(n=9, board="Rings", t="word", img=["R02/02"], word="Graphic.",
         sub="BLACK ENAMEL, RAISED GOLD PIPS",
         title="Domino Bar Ring in Black and Cream Enamel, Graphic Solid Gold Ring",
         desc="Black enamel is the season's graphic accent, and the domino gives it a reason to be there. A gold line splits the tile, the pips are raised polished gold, and the ring sits flat across the finger. Tile 5 x 10 mm, solid gold, US 3 to 16. Shop on Etsy.",
         alt="Hand wearing a gold bar ring with a black and cream enamel domino tile and gold pips",
         link="R02", pr="low"),
    dict(n=10, board="Studo Jewelry", t="story", img=["E02/02"], label="STORY · THE MISMATCHED PAIR",
         body="Black on one ear, cream on the other, the gold pips counting one and two. The pair is meant to differ: a small joke that looks considered.",
         foot="DOMINO FAMILY · FW 26/27",
         title="Mismatched Domino Stud Earrings: Why Our Pair Is Meant to Differ",
         desc="Our Domino studs are deliberately mismatched: one black, one cream, with gold pips counting one and two. A small joke that still looks considered, and an easy way into the mix and match earring trend. Solid gold posts, butterfly backs, sold as a pair. Read the story.",
         alt="Ear wearing a small black enamel domino stud with gold pips",
         link="E02", pr="high"),
    dict(n=11, board="Studo Jewelry", t="guide", img=["E02"], head="How to wear mismatched earrings",
         items=["01  Keep the metal the same", "02  Let one detail repeat", "03  Keep the rest of the ear quiet"],
         foot="STYLING NOTES · ARTIFACT STUDIO",
         title="How to Wear Mismatched Earrings: 3 Rules That Always Work",
         desc="Mismatched earrings look intentional when something ties them together. Keep the metal the same on both ears, let one detail repeat (a shape, a colour, a gold pip), and keep the rest of the ear quiet so the pair reads as a pair. Save these tips for your next earring stack.",
         alt="Two domino stud earrings in solid gold, one black enamel and one cream enamel, with gold pips",
         link="E02", pr="high"),
    dict(n=12, board="Necklaces", t="editorial", img=["N02"], label="N° 02 · DOMINO DROP",
         head="A small graphic poster for the neckline", foot="BLACK & CREAM ENAMEL · SOLID GOLD",
         title="Domino Pendant Necklace in Black and Cream Enamel, Graphic Gold Necklace",
         desc="Hung upright, the domino reads like a small graphic poster at the neckline: three gold pips on black over five on cream, divided by a polished gold line. 7 x 14 mm tile on a 1.2 mm solid gold cable chain, 16, 18 or 20 inches. Tap to shop.",
         alt="Gold domino pendant with black and cream enamel halves and gold pips on a fine chain",
         link="N02", pr="low"),
    dict(n=13, board="Bracelets", t="editorial", img=["B02/02"], label="FIVE TILES",
         head="It moves like a strand, not a bar", foot="BLACK · CREAM · BLACK · CREAM · BLACK",
         title="Domino Link Bracelet with Black and Cream Enamel Tiles, Solid Gold",
         desc="Short lengths of fine chain join five flat enamel tiles, so the bracelet moves like a strand, not a stiff bar. Black, cream, black, cream, black, each with its own count of gold pips. Solid gold, 6.5, 7 or 7.5 inches. Shop on Etsy.",
         alt="Wrist wearing a gold link bracelet with five small black and cream enamel domino tiles",
         link="B02", pr="low"),
    dict(n=14, board="Rings", t="diptych", img=["R02/04", "R02"], focus=[0.5, 0.5],
         label="UP CLOSE", head="Flat glass, raised gold pips",
         title="Black Enamel Domino Ring Close Up, Modern Minimalist Gold Ring",
         desc="Up close the domino ring shows how it is made: flat, glossy black and cream enamel set flush in the gold, with the pips raised in polished gold. A graphic ring for someone who likes modern design and game nights. Solid gold, made to order.",
         alt="Macro of black and cream enamel with raised gold pips above the full domino bar ring",
         link="R02", pr="low"),
    dict(n=15, board="Studo Jewelry", t="quad", img=fam("02"), label="THE DOMINO FAMILY",
         head="Game night, cast in solid gold",
         title="Black and Cream Domino Jewelry Set: Ring, Necklace, Studs and Bracelet",
         desc="The Domino family: a bar ring, a drop necklace, mismatched studs and a link bracelet in black and cream enamel with gold pips. Graphic, modern and made to coordinate. A clever gift for the friend who hosts game night. Explore on Etsy.",
         alt="Four domino enamel pieces in gold: a bar ring, a pendant, mismatched studs and a tile bracelet",
         link=SHOP, pr="low"),
    dict(n=16, board="Studo Jewelry", t="guide", img=["N02/04"], head="What is kiln-fired enamel?",
         items=["01  Glass fused to gold in a kiln", "02  Set flush in recessed cells", "03  A polished gold rim on each"],
         foot="MATERIAL NOTES · ARTIFACT STUDIO",
         title="What Is Enamel Jewelry? How Kiln-Fired Enamel on Gold Is Made",
         desc="Enamel is glass. Ground glass is fired in a kiln until it fuses to the gold, set flush into small recessed cells, each framed by a polished gold rim. The colour stays. Because it is glass it can chip on a hard knock, so treat it like a fine watch face. Save this guide.",
         alt="Macro of flat glossy black and cream enamel set in recessed cells with polished gold rims",
         link=SHOP, pr="high"),

    # ─────────────── 03 CHERRY · oxblood red ───────────────
    dict(n=17, board="Rings", t="editorial", img=["R03"], label="N° 03 · CHERRY PAIR",
         head="Two cherries on a curved gold stem", foot="OXBLOOD ENAMEL · STACKABLE",
         title="Cherry Ring in Solid Gold with Oxblood Red Enamel, Dainty Stacking Ring",
         desc="Two 4 mm oxblood cherries side by side on a curved gold stem, low enough to stack. Oxblood is the winter red, darker and warmer than a summer cherry. Solid 10K, 14K or 18K gold, US 3 to 16 with half sizes. Tap to shop on Etsy.",
         alt="Dainty gold ring with two small oxblood red enamel cherries on a curved gold stem",
         link="R03", pr="low"),
    dict(n=18, board="Necklaces", t="word", img=["N03/02"], word="Oxblood.",
         sub="THE WINTER RED, DARKER THAN SUMMER",
         title="Oxblood Red Cherry Necklace, Enamel Fruit Pendant in Solid Gold",
         desc="Deep red glass, polished gold rims, nothing else. The stem forms the bail, so the two 6 mm cherries swing a little as you move. On a 1.2 mm solid gold cable chain, 16, 18 or 20 inches. A holiday piece you can wear all winter. Shop on Etsy.",
         alt="Woman wearing a small oxblood red enamel cherry pendant on a fine gold chain",
         link="N03", pr="low"),
    dict(n=19, board="Bracelets", t="story", img=["B03/07"], label="STORY · ONLY THE COLOUR",
         body="The quietest piece of the family keeps only the colour of the cherry: five small drops of red, spaced along a fine gold chain.",
         foot="CHERRY FAMILY · FW 26/27",
         title="The Quietest Cherry: a Minimal Red Dot Bracelet in Solid Gold",
         desc="Sometimes the colour is enough. Our Cherry Scatter bracelet keeps only the cherry's oxblood red: five 3.5 mm enamel dots spaced along a 1.1 mm solid gold cable chain. The easiest piece of the family to wear every day and to stack. Read the story.",
         alt="Fine gold chain bracelet with five small oxblood red enamel dots in a ceramic dish",
         link="B03", pr="high"),
    dict(n=20, board="Studo Jewelry", t="guide", img=["E03/02"], head="Huggie hoops: 3 things to know",
         items=["01  They hug the lobe", "02  A hinge, no tools needed", "03  A charm that moves"],
         foot="EARRING NOTES · ARTIFACT STUDIO",
         title="What Are Huggie Earrings? 3 Things to Know Before You Buy Huggie Hoops",
         desc="Huggies are small hoops that sit close to the lobe instead of hanging below it. A hinged click closure opens and closes without tools, and the small size makes them an easy everyday hoop. Our Cherry huggies are 11 mm with a 5 mm oxblood cherry charm. Save this guide.",
         alt="Ear wearing a small gold huggie hoop with a tiny red enamel cherry charm",
         link="E03", pr="high"),
    dict(n=21, board="Studo Jewelry", t="diptych", img=["E03", "E03/05"], focus=[0.5, 0.5],
         label="HUGGIE · CHARM", head="A cherry that moves beneath the hoop",
         title="Cherry Huggie Hoop Earrings with Red Enamel Charm, Solid Gold",
         desc="A clean 11 mm hoop that hugs the lobe and a single 5 mm oxblood cherry that moves beneath it. Hinged solid gold huggies with a click closure, sold as a pair. Cute, festive and still grown up. Shop on Etsy.",
         alt="Pair of gold huggie hoops with red enamel cherry charms above one earring on a fingertip for scale",
         link="E03", pr="low"),
    dict(n=22, board="Necklaces", t="editorial", img=["N03"], label="THE STEM IS THE BAIL",
         head="Two cherries that swing a little as you move", foot="TWO 6 MM CHERRIES · SOLID GOLD",
         title="Cherry Charm Necklace, Red Enamel Cherries on a Solid Gold Chain",
         desc="The gold stem loops into the bail, so the two cherries hang freely and swing a little when you move. Deep oxblood glass framed by polished gold rims. Solid gold chain in 16, 18 or 20 inches. Tap to shop.",
         alt="Gold necklace with two oxblood red enamel cherries hanging from a gold stem bail",
         link="N03", pr="low"),
    dict(n=23, board="Studo Jewelry", t="quad", img=fam("03"), label="THE CHERRY FAMILY",
         head="Holiday red, four ways",
         title="Cherry Jewelry Set in Oxblood Enamel: Ring, Necklace, Huggies, Bracelet",
         desc="The Cherry family in oxblood red enamel and solid gold: a pair ring, a charm necklace, huggie hoops and a scatter bracelet. Playful for the holidays, deep enough in colour to wear all winter. Explore on Etsy.",
         alt="Four oxblood red cherry enamel pieces in gold: a ring, a pendant, huggie hoops and a dot bracelet",
         link=SHOP, pr="low"),
    dict(n=24, board="Rings", t="editorial", img=["R03/08"], label="STOCKING SIZE",
         head="A small red gift for December", foot="GIFT MESSAGE AT CHECKOUT",
         title="Cherry Ring Gift for Her, Small Red Enamel Ring in a Gift Box",
         desc="A little oxblood cherry ring in a linen lined box: a small gift that feels personal. Add a gift message at checkout and it ships with the piece, free within the United States. Made to order in solid gold. Shop the cherry ring on Etsy.",
         alt="Gold cherry ring with red enamel in an open linen lined gift box with a cream ribbon",
         link="R03", pr="low"),

    # ─────────────── 04 BUTTON · Fresh Purple ───────────────
    dict(n=25, board="Rings", t="story", img=["R04/03"], label="STORY · FROM THE COAT",
         body="Taken from winter knitwear and tailoring: a small coat button, remade in purple glass and gold. The four holes go right through, so light shows through the top.",
         foot="BUTTON FAMILY · FW 26/27",
         title="The Button Ring: How a Coat Button Became Purple Enamel Jewelry",
         desc="Our Button family starts with winter knitwear and tailoring. The small coat button is remade in Fresh Purple glass and solid gold, and its four holes go right through so light shows through the top. A ring for anyone who sews, knits or loves a good coat. Read the story.",
         alt="Hand in a knit sleeve wearing a gold ring topped with a purple enamel button with four holes",
         link="R04", pr="high"),
    dict(n=26, board="Studo Jewelry", t="guide", img=["R04/04"], head="How to care for enamel jewelry",
         items=["01  Take it off for the gym", "02  Keep it away from the dishes", "03  Wipe with a soft cloth"],
         foot="ENAMEL IS GLASS FUSED TO GOLD",
         title="How to Care for Enamel Jewelry: 3 Simple Rules to Keep It Bright",
         desc="Enamel is glass fused to gold. It keeps its colour for years, but glass can chip on a hard knock. Take enamel rings and bracelets off for the gym and the dishes, store them apart from other pieces, and wipe them with a soft cloth. Save this care guide.",
         alt="Macro of a purple enamel button ring with four open holes and a polished gold rim",
         link=SHOP, pr="high"),
    dict(n=27, board="Bracelets", t="editorial", img=["B04/06"], label="THE BUTTON IS THE CLASP",
         head="Fastens at the front, like a coat", foot="EASY TO DO UP WITH ONE HAND",
         title="Button Toggle Bracelet, Purple Enamel Front Clasp Bracelet in Gold",
         desc="The enamel button is the clasp: it passes through a polished gold loop at the front of the wrist, the way a coat fastens. Easy to do up with one hand. 10 mm Fresh Purple button on a 1.1 mm solid gold cable chain, 6.5, 7 or 7.5 inches. Shop on Etsy.",
         alt="Close view of a purple enamel button passing through a gold loop as a bracelet clasp",
         link="B04", pr="low"),
    dict(n=28, board="Necklaces", t="editorial", img=["N04/02"], label="A PURPLE BUTTON ON A GOLD RING",
         head="Tailored, for knitwear season", foot="BUTTON 12 MM · SOLID GOLD CHAIN",
         title="Purple Button Pendant Necklace, Enamel Button Charm in Solid Gold",
         desc="The button hangs from a small gold ring through one of its holes, so it tilts slightly, like a coat hung on a hook. 12 mm Fresh Purple enamel button on a 1.2 mm solid gold chain. A tailored detail for knitwear season. Tap to shop.",
         alt="Woman wearing a purple enamel button pendant on a fine gold chain",
         link="N04", pr="low"),
    dict(n=29, board="Studo Jewelry", t="editorial", img=["E04/02"], label="N° 04 · BUTTON STUDS",
         head="A clear shot of colour with a tailored edge", foot="6 MM · FLAT TO THE LOBE",
         title="Purple Button Stud Earrings, Tiny Violet Enamel Studs in Solid Gold",
         desc="The button at its smallest: 6 mm, flat to the lobe. A clear shot of Fresh Purple with a tailored gold edge. Solid gold posts with butterfly backs, sold as a pair. Easy to wear with everything from knitwear to a blazer. Shop on Etsy.",
         alt="Earlobe wearing a tiny purple enamel button stud earring in gold",
         link="E04", pr="low"),
    dict(n=30, board="Necklaces", t="diptych", img=["N04", "N04/07"], focus=[0.5, 0.5],
         label="HUNG FROM ONE HOLE", head="Tilted, like a coat on a hook",
         title="Button Necklace in Purple Enamel and Gold, a Gift for Knitters",
         desc="A small purple button hung from one hole so it tilts, the way a coat hangs on a hook. Solid gold and Fresh Purple enamel, made to order. A thoughtful gift for a knitter, a tailor or anyone who loves a good coat. Explore on Etsy.",
         alt="Purple enamel button pendant on a gold chain above the pendant resting in a ceramic dish",
         link="N04", pr="low"),
    dict(n=31, board="Studo Jewelry", t="quad", img=fam("04"), label="THE BUTTON FAMILY",
         head="Knitwear season, in purple and gold",
         title="Purple Button Jewelry Set: Ring, Necklace, Studs and Toggle Bracelet",
         desc="The Button family in Fresh Purple enamel and solid gold: a button ring, a pendant necklace, button studs and a bracelet that fastens with the button. Borrowed from winter tailoring, made to be worn together or alone. Explore on Etsy.",
         alt="Four purple enamel button pieces in gold: a ring, a pendant, stud earrings and a toggle bracelet",
         link=SHOP, pr="low"),
    dict(n=32, board="Rings", t="editorial", img=["R04/08"], label="FOR THE ONE WHO SEWS",
         head="A button that never falls off", foot="GIFT MESSAGE AT CHECKOUT",
         title="Button Ring Gift for Knitters and Sewists, Purple Enamel Gold Ring",
         desc="For the friend who sews, knits or keeps a button tin: a purple enamel button ring that will never fall off. Solid gold, made to order, ships free within the United States with an optional gift message. Shop on Etsy.",
         alt="Purple enamel button ring in an open linen lined gift box on a pale oak table",
         link="R04", pr="low"),

    # ─────────────── 05 ACORN · Cocoa Powder ───────────────
    dict(n=33, board="Rings", t="editorial", img=["R05"], label="N° 05 · ACORN RING",
         head="Flat brown glass under a textured gold cap", foot="COCOA ENAMEL · 6 X 8 MM",
         title="Acorn Ring in Solid Gold with Brown Enamel, Autumn Woodland Ring",
         desc="The acorn body is flat Cocoa Powder glass, the cap is gold with a fine crosshatch, so the two surfaces play against each other. 6 x 8 mm, solid 10K, 14K or 18K gold, US 3 to 16. An autumn ring you can wear all year. Tap to shop.",
         alt="Gold ring topped with a small acorn in brown enamel with a textured gold cap",
         link="R05", pr="low"),
    dict(n=34, board="Necklaces", t="story", img=["N05/03"], label="STORY · THE OLDEST SHAPE",
         body="Cocoa Powder is the season's brown, and the acorn is its oldest shape. Flat glass for the body, a crosshatched gold cap, two surfaces set against each other.",
         foot="ACORN FAMILY · FW 26/27",
         title="Why the Acorn? The Story of Our Brown Enamel Autumn Jewelry",
         desc="The acorn may be the oldest autumn shape there is. Our Acorn family pairs a flat body of Cocoa Powder brown enamel with a finely crosshatched gold cap, so matte texture and glossy glass play against each other. A small collectible for the season. Read the story.",
         alt="Woman in an oatmeal wool sweater wearing a small brown enamel acorn pendant",
         link="N05", pr="high"),
    dict(n=35, board="Bracelets", t="guide", img=["B05/02"], head="Three ways to wear brown this autumn",
         items=["01  With cream knitwear", "02  With camel and warm gold", "03  With one bright accent"],
         foot="STYLING NOTES · ARTIFACT STUDIO",
         title="How to Wear Brown This Autumn: 3 Easy Outfit and Jewelry Ideas",
         desc="Brown is the easiest colour of the season once you pair it well. Wear it with cream knitwear for softness, with camel and warm yellow gold for depth, or add one bright accent like teal or chartreuse. Our Acorn pieces bring cocoa enamel to the wrist. Save these ideas.",
         alt="Wrist wearing a gold chain bracelet with two small brown enamel acorn charms",
         link="B05", pr="high"),
    dict(n=36, board="Studo Jewelry", t="word", img=["E05/02"], word="Woodland.",
         sub="A SHORT DROP THAT MOVES, NOT SWINGS",
         title="Acorn Drop Earrings, Brown Enamel Autumn Dangle Earrings in Solid Gold",
         desc="A short drop, about 17 mm in all, so the acorns move without swinging. Textured gold caps, flat Cocoa Powder glass bodies, solid gold posts with butterfly backs. A woodland earring for autumn walks and holiday dinners. Shop on Etsy.",
         alt="Ear wearing a small gold drop earring with a brown enamel acorn",
         link="E05", pr="low"),
    dict(n=37, board="Bracelets", t="diptych", img=["B05", "B05/05"], focus=[0.5, 0.5],
         label="PICKED ON THE SAME WALK", head="Two acorns, one slightly lower",
         title="Acorn Charm Bracelet, Dainty Brown Enamel Nature Bracelet in Gold",
         desc="A pair of 5 x 7 mm acorns at the centre of the wrist, one slightly lower than the other, like two picked on the same walk. Fine 1.1 mm solid gold cable chain, 6.5, 7 or 7.5 inches. Tap to shop.",
         alt="Gold chain bracelet with two brown enamel acorn charms above the bracelet on an open palm",
         link="B05", pr="low"),
    dict(n=38, board="Necklaces", t="editorial", img=["N05/06"], label="HANGS STRAIGHT, TURNS A LITTLE",
         head="A small collectible for the season", foot="ACORN 8 X 12 MM · SOLID GOLD",
         title="Acorn Pendant Necklace in Brown Enamel, Woodland Charm on Gold Chain",
         desc="The stem loops into its own bail, so the acorn hangs straight and turns a little as you move. 8 x 12 mm in Cocoa Powder enamel with a textured gold cap, on a 1.2 mm solid gold chain. Shop the acorn necklace on Etsy.",
         alt="Side view of a brown enamel acorn pendant with a gold cap hanging on a fine chain",
         link="N05", pr="low"),
    dict(n=39, board="Studo Jewelry", t="quad", img=fam("05"), label="THE ACORN FAMILY",
         head="Autumn, collected in gold",
         title="Acorn Jewelry Set in Brown Enamel: Ring, Necklace, Earrings, Bracelet",
         desc="The Acorn family in Cocoa Powder enamel and solid gold: a ring, a drop necklace, drop earrings and a charm bracelet. Each acorn has a flat glass body and a crosshatched gold cap. A collectible autumn set. Explore on Etsy.",
         alt="Four brown enamel acorn pieces in gold: a ring, a pendant, drop earrings and a charm bracelet",
         link=SHOP, pr="low"),
    dict(n=40, board="Studo Jewelry", t="editorial", img=["E05/04"], label="UP CLOSE",
         head="Crosshatched gold, flat cocoa glass", foot="ACORN DROP EARRINGS",
         title="Brown Enamel Acorn Earrings Close Up, Textured Gold Cap Detail",
         desc="Up close you can see the two surfaces of every acorn: a finely crosshatched gold cap and a flat, glossy body of Cocoa Powder enamel. Small details like this are why we make each piece to order. Shop the acorn earrings on Etsy.",
         alt="Macro of a brown enamel acorn earring with a crosshatched gold cap",
         link="E05", pr="low"),

    # ─────────────── 06 CHECKER · Green Glow + Wax Paper cream ───────────────
    dict(n=41, board="Rings", t="word", img=["R06/02"], word="Check.",
         sub="NINE CELLS IN A FINE GOLD GRID",
         title="Checkerboard Signet Ring, Chartreuse and Cream Enamel in Solid Gold",
         desc="Green Glow is the season's brightest colour; set against cream inside a fine gold grid it becomes graphic rather than loud. Nine small flat cells on an 8 x 8 mm signet top. Solid gold, US 3 to 16. Shop on Etsy.",
         alt="Hand wearing a square gold signet ring with a chartreuse and cream enamel checkerboard",
         link="R06", pr="low"),
    dict(n=42, board="Necklaces", t="story", img=["N06"], label="STORY · THE PINWHEEL",
         body="Turn a checkered square 45 degrees and cross it with one gold line: it becomes four alternating triangles, a small pinwheel of colour at the neckline.",
         foot="CHECKER FAMILY · FW 26/27",
         title="How a Checkerboard Became a Pinwheel: Our Chartreuse Enamel Necklace",
         desc="Take a checkered square, hang it on its point and cross it with one gold line from point to point. It becomes four alternating triangles of chartreuse and cream, a small pinwheel of colour at the neckline. 10 mm, solid gold. Read the story behind the Checker Diamond necklace.",
         alt="Gold diamond shaped pendant with four alternating chartreuse and cream enamel triangles",
         link="N06", pr="high"),
    dict(n=43, board="Rings", t="guide", img=["R06/03"], head="How to wear bright colour in winter",
         items=["01  Pair it with cream", "02  Keep it small and flat", "03  Repeat it once, not twice"],
         foot="STYLING NOTES · ARTIFACT STUDIO",
         title="How to Wear Bright Colour in Winter: 3 Styling Rules for Colourful Jewelry",
         desc="Bright colour works in winter when it has room. Pair it with cream or oatmeal, keep the piece small and flat so it reads as an accent, and repeat the colour once (a scarf, a bag) rather than everywhere. Our chartreuse Checker pieces are made for exactly this. Save these rules.",
         alt="Hand around a stoneware mug wearing a chartreuse checkerboard signet ring, cream knit sleeve",
         link="R06", pr="high"),
    dict(n=44, board="Studo Jewelry", t="editorial", img=["E06/02"], label="N° 06 · CHECKER MINIS",
         head="Four cells of colour, flat against the lobe", foot="5 X 5 MM · SOLID GOLD POSTS",
         title="Checker Mini Stud Earrings, Tiny Square Chartreuse Enamel Studs",
         desc="The checker at 5 mm: four cells of chartreuse and cream set flat against the lobe, a small graphic accent. Solid gold posts with butterfly backs, sold as a pair. A fun second hole stud. Shop on Etsy.",
         alt="Earlobe wearing a tiny square stud with chartreuse and cream enamel checks",
         link="E06", pr="low"),
    dict(n=45, board="Bracelets", t="editorial", img=["B06/02"], label="ONE LINE OF THE BOARD",
         head="A 16 mm checker bar across the wrist", foot="FOUR CELLS · 1.1 MM CABLE CHAIN",
         title="Checker Bar Bracelet, Chartreuse and Cream Enamel on a Gold Chain",
         desc="One line of the checkerboard, 16 mm long, sitting flat across the top of the wrist. Four enamel cells in chartreuse and cream on a fine solid gold cable chain, 6.5, 7 or 7.5 inches. Graphic, light and easy to stack. Tap to shop.",
         alt="Wrist wearing a thin gold chain bracelet with a small checkered chartreuse and cream bar",
         link="B06", pr="low"),
    dict(n=46, board="Rings", t="diptych", img=["R06/04", "R06/06"], focus=[0.5, 0.5],
         label="TOP · SIDE", head="Nine flat cells, top and side",
         title="Enamel Checkerboard Ring Detail, Low Square Signet in Solid Gold",
         desc="From the top, nine flat cells of chartreuse and cream in a fine gold grid. From the side, a low square signet that sits close to the finger. Solid gold, made to order, US 3 to 16 with half sizes. Explore on Etsy.",
         alt="Macro of a chartreuse and cream checkerboard enamel ring top above the signet lying on its side",
         link="R06", pr="low"),
    dict(n=47, board="Studo Jewelry", t="quad", img=fam("06"), label="THE CHECKER FAMILY",
         head="Chartreuse and cream, made graphic",
         title="Checkerboard Jewelry Set in Chartreuse Enamel: Ring, Necklace, Studs, Bracelet",
         desc="The Checker family in Green Glow chartreuse and cream enamel on solid gold: a signet ring, a diamond pendant, mini studs and a bar bracelet. Bright, graphic and small enough to wear every day. Explore the set on Etsy.",
         alt="Four chartreuse and cream checker enamel pieces in gold: a signet, a pendant, studs and a bar bracelet",
         link=SHOP, pr="low"),
    dict(n=48, board="Studo Jewelry", t="editorial", img=["E06/05"], label="SECOND HOLE",
         head="Small enough for a second piercing", foot="CHECKER MINI STUDS · 5 MM",
         title="Tiny Enamel Studs for a Second Piercing, Chartreuse Checker Earrings",
         desc="Looking for a small stud for a second or third hole? The Checker minis are 5 x 5 mm, flat to the lobe, with solid gold posts and butterfly backs. A graphic little pop of chartreuse for a curated ear. Shop on Etsy.",
         alt="Tiny chartreuse and cream checker stud earring on a fingertip for scale",
         link="E06", pr="low"),

    # ─────────────── 07 CRUSH · berry pink ───────────────
    dict(n=49, board="Necklaces", t="editorial", img=["N07"], label="N° 07 · CRUSH HEART",
         head="A heart with a little lean to it", foot="BERRY ENAMEL · 10 MM · SOLID GOLD",
         title="Berry Pink Heart Necklace, Enamel Heart Pendant in Solid Gold",
         desc="A heart with a little lean to it, deep berry glass in a polished gold rim. A winter gift that runs straight into Valentine's Day. 10 mm on a 1.2 mm solid gold chain, 16, 18 or 20 inches. Tap to shop on Etsy.",
         alt="Gold pendant with a slightly lopsided berry pink enamel heart on a fine chain",
         link="N07", pr="low"),
    dict(n=50, board="Rings", t="story", img=["R07/02"], label="STORY · DRAWN BY HAND",
         body="The heart is drawn a little off balance on purpose, like one sketched in the margin of a notebook. Berry is the deep winter pink, not a pastel.",
         foot="CRUSH FAMILY · FW 26/27",
         title="Why Our Heart Is Lopsided: the Story of the Crush Heart Ring",
         desc="A perfect heart looks printed. Ours is drawn a little off balance on purpose, like one sketched in the margin of a notebook, and filled with berry pink, the deep winter pink rather than a pastel. A 6 mm heart on a thin stacking ring in solid gold. Read the story.",
         alt="Hand wearing a thin gold stacking ring with a small berry pink enamel heart",
         link="R07", pr="high"),
    dict(n=51, board="Bracelets", t="guide", img=["B07/02"], head="How to find your bracelet size",
         items=["01  Measure your wrist snugly", "02  Add about half an inch", "03  Choose 6.5, 7 or 7.5 in"],
         foot="SIZING NOTES · ARTIFACT STUDIO",
         title="How to Measure Your Wrist for a Bracelet: Easy Sizing Guide",
         desc="Wrap a soft tape or a strip of paper snugly around your wrist bone and measure it. Add about half an inch for a close, comfortable fit, then pick the nearest size. Most of our enamel bracelets come in 6.5, 7 or 7.5 inches. Save this sizing guide before you order.",
         alt="Wrist wearing a slim open gold cuff with a small berry pink enamel heart",
         link="B07", pr="high"),
    dict(n=52, board="Studo Jewelry", t="word", img=["E07/02"], word="Crush.",
         sub="HEARTS ON 15 MM OF FINE CHAIN",
         title="Pink Heart Drop Earrings, Berry Enamel Heart Dangles in Solid Gold",
         desc="Each 7 mm berry heart hangs on 15 mm of fine gold chain, so it moves and catches the light with every turn of the head. Solid gold posts with butterfly backs, sold as a pair. Shop the Crush heart earrings on Etsy.",
         alt="Ear wearing a gold chain drop earring with a small berry pink enamel heart",
         link="E07", pr="low"),
    dict(n=53, board="Bracelets", t="editorial", img=["B07/06"], label="OPEN CUFF · 1.6 MM",
         head="Slips on from the side, heart where the wrist turns", foot="6.5 · 7 · 7.5 IN INNER",
         title="Slim Open Cuff Bracelet with Pink Enamel Heart, Solid Gold Bangle",
         desc="A 1.6 mm band of solid gold that slips on from the side, with one small lopsided berry heart where the wrist turns. Choose 6.5, 7 or 7.5 inches inner circumference. Stacks easily with a watch. Tap to shop.",
         alt="Slim open gold cuff with a small berry pink enamel heart lying on linen",
         link="B07", pr="low"),
    dict(n=54, board="Studo Jewelry", t="diptych", img=["N07/08", "R07/08"], focus=[0.5, 0.5],
         label="WINTER INTO VALENTINE'S", head="A heart to give twice a season",
         title="Pink Heart Jewelry Gift Ideas for Christmas and Valentine's Day",
         desc="One heart, two occasions: a berry enamel heart necklace or stacking ring works as a Christmas gift and runs straight into Valentine's Day. Solid gold, made to order, with a gift message at checkout. Explore the Crush family on Etsy.",
         alt="Berry heart pendant in a gift box above a berry heart stacking ring in a gift box",
         link=SHOP, pr="low"),
    dict(n=55, board="Studo Jewelry", t="quad", img=fam("07"), label="THE CRUSH FAMILY",
         head="Berry pink, never pastel",
         title="Pink Heart Jewelry Set in Berry Enamel: Ring, Necklace, Earrings, Cuff",
         desc="The Crush family in berry pink enamel and solid gold: a stacking ring, a heart necklace, heart drop earrings and a slim open cuff. Every heart leans a little, as if drawn by hand. Explore the set on Etsy.",
         alt="Four berry pink enamel heart pieces in gold: a ring, a pendant, drop earrings and an open cuff",
         link=SHOP, pr="low"),
    dict(n=56, board="Rings", t="editorial", img=["R07/05"], label="STACKING RING",
         head="A 6 mm heart for the middle of a stack", foot="THIN GOLD BAND · US 3 TO 16",
         title="Dainty Heart Stacking Ring, Berry Pink Enamel on a Thin Gold Band",
         desc="Small enough to sit in the middle of a stack: a 6 mm berry heart on a thin solid gold band. Wear it alone or between plain bands. Solid 10K, 14K or 18K gold, US 3 to 16 with half sizes. Shop on Etsy.",
         alt="Thin gold stacking ring with a small pink enamel heart held between two fingertips",
         link="R07", pr="low"),

    # ─────────────── 08 BOW · ocean navy ───────────────
    dict(n=57, board="Rings", t="editorial", img=["R08"], label="N° 08 · BOW RING",
         head="A tied ribbon, laid flat across the finger", foot="NAVY ENAMEL · 10 X 6 MM",
         title="Navy Bow Ring in Solid Gold, Blue Enamel Ribbon Ring",
         desc="The bow stays flat and graphic: two navy loops, a polished gold knot, short tails. It sits across the finger like a tied ribbon. 10 x 6 mm, solid 10K, 14K or 18K gold, US 3 to 16. Tap to shop on Etsy.",
         alt="Gold ring with a flat navy blue enamel bow and a polished gold knot",
         link="R08", pr="low"),
    dict(n=58, board="Necklaces", t="story", img=["N08/02"], label="STORY · JUST TIED",
         body="The chain runs through a small bail behind the gold knot, so the bow sits straight at the collarbone, like a gift that has just been tied.",
         foot="BOW FAMILY · FW 26/27",
         title="The Bow Necklace, Grown Up: a Navy Enamel Ribbon in Solid Gold",
         desc="The bow trend, grown up for winter. Our navy bow hangs from a small bail hidden behind the gold knot, so it sits straight at the collarbone like a gift that has just been tied. 12 x 9 mm on a solid gold chain. Read the story of the Bow family.",
         alt="Navy enamel bow pendant with a gold knot worn just below the collarbone on a fine gold chain",
         link="N08", pr="high"),
    dict(n=59, board="Studo Jewelry", t="guide", img=["E08/08"], head="Buying jewelry as a gift? Start here",
         items=["01  Studs need no size", "02  18 in is the safe length", "03  7 in fits most wrists"],
         foot="GIFT NOTES · ARTIFACT STUDIO",
         title="Jewelry Gift Guide: How to Choose Without Knowing Their Size",
         desc="Buying jewelry for someone else? Stud earrings need no size at all. For a necklace, 18 inches is the safest everyday length. For a bracelet, 7 inches fits most wrists. Rings are the only piece that needs a real size, so keep them for when you can ask. Save this gift guide.",
         alt="Navy enamel bow stud earrings in an open linen lined gift box",
         link=SHOP, pr="high"),
    dict(n=60, board="Bracelets", t="word", img=["B08/02"], word="Always.",
         sub="THE BOW YOU NEVER TAKE OFF",
         title="Dainty Bow Bracelet, Navy Enamel Ribbon Charm on a Solid Gold Chain",
         desc="One small navy bow on a fine gold chain: the kind of piece that becomes the one you never take off. 6 x 4 mm bow, 1.1 mm solid gold cable chain, 6.5, 7 or 7.5 inches. Shop the bow bracelet on Etsy.",
         alt="Wrist wearing a fine gold chain bracelet with a tiny navy enamel bow",
         link="B08", pr="low"),
    dict(n=61, board="Studo Jewelry", t="editorial", img=["E08/02"], label="N° 08 · BOW STUDS",
         head="Navy keeps the bow grown up", foot="7 X 5 MM · SOLID GOLD POSTS",
         title="Navy Bow Stud Earrings, Blue Enamel Ribbon Studs in Solid Gold",
         desc="The bow at 7 mm, flat to the ear, polished gold knot in the middle. Navy keeps it grown up. Solid gold posts with butterfly backs, sold as a pair. A coquette detail for work and weekends. Tap to shop.",
         alt="Earlobe wearing a small navy enamel bow stud with a gold knot",
         link="E08", pr="low"),
    dict(n=62, board="Necklaces", t="diptych", img=["N08", "N08/03"], focus=[0.5, 0.5],
         label="NAVY · GOLD", head="The bow, grown up for winter",
         title="Navy Bow Pendant Necklace, Coquette Jewelry in Solid Gold",
         desc="A flat navy bow with a polished gold knot, worn at the collarbone with winter knitwear. Coquette, but grown up. 12 x 9 mm on a 1.2 mm solid gold chain, 16, 18 or 20 inches. Explore on Etsy.",
         alt="Navy enamel bow pendant on a gold chain above a woman wearing it with a camel coat",
         link="N08", pr="low"),
    dict(n=63, board="Studo Jewelry", t="quad", img=fam("08"), label="THE BOW FAMILY",
         head="Coquette, in navy and solid gold",
         title="Navy Bow Jewelry Set: Bow Ring, Necklace, Stud Earrings and Bracelet",
         desc="The Bow family in ocean navy enamel and solid gold: a bow ring, a pendant necklace, bow studs and a dainty bracelet. Flat, graphic ribbons with a polished gold knot. Explore the set on Etsy.",
         alt="Four navy enamel bow pieces in gold: a ring, a pendant, stud earrings and a chain bracelet",
         link=SHOP, pr="low"),
    dict(n=64, board="Rings", t="editorial", img=["R08/09"], label="THREE GOLDS · ONE BOW",
         head="Choose the gold, keep the navy", foot="10K · 14K · 18K · MADE TO ORDER",
         title="Bow Ring in Yellow, White or Rose Gold with Navy Enamel",
         desc="The navy bow ring shown in yellow, white and rose gold. Yellow makes the navy warmer, white gold makes it crisp, rose makes it soft. Choose 10K, 14K or 18K. Which gold is yours? Tap to choose on Etsy.",
         alt="Three navy enamel bow rings in yellow, white and rose gold side by side",
         link="R08", pr="low"),

    # ─────────────── 09 GINKGO · moss green ───────────────
    dict(n=65, board="Necklaces", t="editorial", img=["N09/02"], label="N° 09 · GINKGO LARIAT",
         head="A long line that frames the neckline", foot="LEAF 10 MM · 30 MM DROP",
         title="Ginkgo Lariat Necklace, Moss Green Enamel Leaf Y Necklace in Gold",
         desc="The drop falls from the centre of the chain and the ginkgo leaf turns at its end, so the necklace frames the neckline in one long line. 10 mm moss green leaf on a 30 mm drop, solid gold chain in 16, 18 or 20 inches. Shop on Etsy.",
         alt="Woman wearing a gold Y necklace with a moss green enamel ginkgo leaf at the end of the drop",
         link="N09", pr="low"),
    dict(n=66, board="Rings", t="story", img=["R09/03"], label="STORY · THE FAN LEAF",
         body="The ginkgo fan is split at its centre by a polished gold vein. On the finger the two ends pass each other, so the ring reads light and a little asymmetric.",
         foot="GINKGO FAMILY · FW 26/27",
         title="The Ginkgo Leaf Ring: an Open Bypass Ring in Moss Green Enamel",
         desc="The ginkgo is one of the oldest trees on earth and its fan shaped leaf is unmistakable. Our open ring splits the moss green leaf with a polished gold vein, and the two ends pass each other on the finger for a light, asymmetric line. Solid gold. Read the story.",
         alt="Hand in a knit sleeve wearing an open gold ring with a moss green enamel ginkgo leaf",
         link="R09", pr="high"),
    dict(n=67, board="Necklaces", t="guide", img=["N09"], head="Which neckline for a lariat necklace?",
         items=["01  V-neck · follows the line", "02  Open collar · fills the gap", "03  Crew neck · wear it on top"],
         foot="STYLING NOTES · ARTIFACT STUDIO",
         title="How to Wear a Lariat Necklace: the Best Necklines for a Y Necklace",
         desc="A lariat or Y necklace draws a long vertical line. With a V-neck it follows the neckline, with an open collar it fills the gap, and over a crew neck knit it becomes the focal point. Choose 18 inches for most necklines. Save this styling guide.",
         alt="Gold lariat necklace with a moss green enamel ginkgo leaf drop on linen",
         link="N09", pr="high"),
    dict(n=68, board="Studo Jewelry", t="word", img=["E09/02"], word="Autumn.",
         sub="GINKGO LEAVES THAT TURN AS YOU DO",
         title="Ginkgo Leaf Drop Earrings, Moss Green Enamel Botanical Earrings",
         desc="Each 9 mm ginkgo leaf hangs from its own gold stem, so the fan turns gently against the neck. Moss green enamel, solid gold posts with butterfly backs, sold as a pair. Botanical earrings for the season of falling leaves. Shop on Etsy.",
         alt="Ear wearing a gold drop earring with a small moss green enamel ginkgo leaf",
         link="E09", pr="low"),
    dict(n=69, board="Bracelets", t="editorial", img=["B09"], label="THREE LEAVES",
         head="Each turned a little, as on one branch", foot="THREE 6 MM LEAVES · SOLID GOLD",
         title="Ginkgo Leaf Bracelet, Three Moss Green Enamel Leaves on a Gold Chain",
         desc="Three moss green ginkgo leaves, each turned a little differently, like ones caught on the same branch. 6 mm leaves on a 1.1 mm solid gold cable chain, 6.5, 7 or 7.5 inches. Tap to shop.",
         alt="Gold chain bracelet with three small moss green enamel ginkgo leaves",
         link="B09", pr="low"),
    dict(n=70, board="Rings", t="diptych", img=["R09", "R09/06"], focus=[0.5, 0.5],
         label="OPEN RING", head="Two ends that pass each other",
         title="Open Leaf Ring in Solid Gold, Moss Green Ginkgo Bypass Ring",
         desc="An open ring: the ginkgo leaf at one end, the gold band passing it at the other. Light on the finger and a little asymmetric. Solid 10K, 14K or 18K gold, US 3 to 16 with half sizes. Explore on Etsy.",
         alt="Open gold ginkgo ring with a moss green enamel leaf above a side view of the open ring",
         link="R09", pr="low"),
    dict(n=71, board="Studo Jewelry", t="quad", img=fam("09"), label="THE GINKGO FAMILY",
         head="Moss green, gathered in gold",
         title="Ginkgo Leaf Jewelry Set in Moss Green Enamel: Ring, Lariat, Earrings, Bracelet",
         desc="The Ginkgo family in moss green enamel and solid gold: an open ring, a lariat necklace, leaf drop earrings and a three leaf bracelet. Botanical, quiet and made for autumn. Explore the set on Etsy.",
         alt="Four moss green ginkgo enamel pieces in gold: an open ring, a lariat, drop earrings and a bracelet",
         link=SHOP, pr="low"),
    dict(n=72, board="Studo Jewelry", t="editorial", img=["E09/07"], label="BOTANICAL",
         head="Leaf drops for the season of falling leaves", foot="GINKGO DROP EARRINGS · 9 MM",
         title="Botanical Gold Earrings with Green Enamel Ginkgo Leaves, Autumn Style",
         desc="A pair of moss green ginkgo leaf drops resting in a ceramic dish with dried eucalyptus: autumn in a small gesture. Solid gold, made to order, sold as a pair. Shop the Ginkgo earrings on Etsy.",
         alt="Pair of moss green enamel ginkgo leaf drop earrings in a small off white ceramic dish",
         link="E09", pr="low"),

    # ─────────────── 10 WICK · Wax Paper cream + amber ───────────────
    dict(n=73, board="Necklaces", t="editorial", img=["N10/02"], label="N° 10 · CANDLE PENDANT",
         head="A bar pendant, until you see the flame", foot="CREAM & AMBER ENAMEL · SOLID GOLD",
         title="Candle Pendant Necklace, Cream and Amber Enamel Bar Pendant in Gold",
         desc="Long and narrow, it reads like a small bar pendant until you see the amber flame at the top. 3 x 14 mm candle with a 3 x 5 mm flame, on a 1.2 mm solid gold chain in 16, 18 or 20 inches. A holiday piece for the dark months. Shop on Etsy.",
         alt="Woman wearing a slim cream enamel candle pendant with an amber flame on a gold chain",
         link="N10", pr="low"),
    dict(n=74, board="Rings", t="story", img=["R10/03"], label="STORY · ONE WARM DROP",
         body="Wax Paper cream, the season's quiet neutral, meets one warm drop of amber. A small candle stands across the band, lit for the dark months.",
         foot="WICK FAMILY · FW 26/27",
         title="The Candle Ring: a Tiny Flame of Amber Enamel for the Dark Months",
         desc="Our Wick family was made for the longest nights of the year. Wax Paper cream, the season's quiet neutral, meets one warm drop of amber: a small candle standing across a thin solid gold band, small enough to stack with anything. Read the story.",
         alt="Hands around a stoneware mug, one wearing a thin gold ring with a small cream enamel candle and amber flame",
         link="R10", pr="high"),
    dict(n=75, board="Rings", t="guide", img=["R10/05"], head="How to find your ring size at home",
         items=["01  Wrap a strip of paper", "02  Mark it, measure in mm", "03  Measure at the end of the day"],
         foot="US 3 TO 16 · WHOLE AND HALF SIZES",
         title="How to Find Your Ring Size at Home: 3 Easy Steps",
         desc="Wrap a thin strip of paper around the base of your finger, mark where it meets, and measure the length in millimetres to compare with a ring size chart. Measure at the end of the day when fingers are largest, and if you fall between two sizes, choose the larger one. Save this guide.",
         alt="Thin gold candle ring held between two fingertips to show its small size",
         link="R10", pr="high"),
    dict(n=76, board="Studo Jewelry", t="word", img=["E10/02"], word="Glow.",
         sub="ONLY THE FLAME, 6 MM TALL",
         title="Flame Stud Earrings, Tiny Amber Enamel Studs in Solid Gold",
         desc="Only the flame from the candle, 6 mm tall, warm against the lobe through the dark months. Amber enamel, solid gold posts with butterfly backs, sold as a pair. A little glow for the holidays. Shop on Etsy.",
         alt="Earlobe wearing a tiny amber enamel flame stud earring in gold",
         link="E10", pr="low"),
    dict(n=77, board="Bracelets", t="editorial", img=["B10"], label="TWIN CANDLES",
         head="One a little taller than the other", foot="8 MM BASE BAR · SOLID GOLD",
         title="Twin Candle Bracelet, Cream and Amber Enamel Holiday Bracelet in Gold",
         desc="A pair of candles at the centre of the wrist, one a little taller than the other, standing on an 8 mm gold base bar. Cream and amber enamel on a fine solid gold chain, 6.5, 7 or 7.5 inches. Tap to shop.",
         alt="Gold chain bracelet with two small cream enamel candles with amber flames on a gold bar",
         link="B10", pr="low"),
    dict(n=78, board="Studo Jewelry", t="diptych", img=["R10/08", "N10/08"], focus=[0.5, 0.5],
         label="LIT FOR THE HOLIDAYS", head="Candles you can wrap",
         title="Candle Jewelry Gifts for the Holidays, Cream and Amber Enamel in Gold",
         desc="Small candles you can wrap: a candle stacking ring or a candle pendant necklace in cream and amber enamel, solid gold, made to order. Add a gift message at checkout and it ships with the piece. Explore the Wick family on Etsy.",
         alt="Candle ring in a gift box above a candle pendant necklace in a gift box",
         link=SHOP, pr="low"),
    dict(n=79, board="Studo Jewelry", t="quad", img=fam("10"), label="THE WICK FAMILY",
         head="Cream, amber and a small flame",
         title="Candle Jewelry Set in Cream and Amber Enamel: Ring, Necklace, Studs, Bracelet",
         desc="The Wick family in Wax Paper cream and amber enamel on solid gold: a candle stacking ring, a candle pendant, flame studs and a twin candle bracelet. Warm little lights for winter. Explore the set on Etsy.",
         alt="Four cream and amber candle enamel pieces in gold: a ring, a pendant, flame studs and a bracelet",
         link=SHOP, pr="low"),
    dict(n=80, board="Studo Jewelry", t="quad", img=["R01", "R03", "R06", "R09"], label="FW 26/27 · ENAMEL",
         head="Ten families, one winter in colour", foot="40 PIECES · SOLID GOLD · MADE TO ORDER",
         title="Colourful Enamel Jewelry for Fall and Winter 2026, Solid Gold Collection",
         desc="Our FW 26/27 enamel collection: ten families, forty pieces, each in one colour of the season. Teal keyholes, oxblood cherries, chartreuse checkers, moss green ginkgo leaves and more, in kiln-fired enamel on solid gold. Made to order. Explore the full collection on Etsy.",
         alt="Four enamel rings in gold: a teal keyhole signet, a red cherry ring, a chartreuse checker signet and a green ginkgo ring",
         link=SHOP, pr="high"),
]

assert len(PINS) == 80 and [p["n"] for p in PINS] == list(range(1, 81))
