#!/usr/bin/env bash
#
# Local dev bootstrap for the Jade Gold NYC panel (Cursor Cloud / fresh VM).
#
# Brings up the local Supabase stack, provisions the schema, writes .env.local,
# and creates a confirmed test user that owns the seeded "Jade Gold NYC" org so
# the app lands straight on the dashboard after login.
#
# Idempotent: safe to re-run. Only (re)provisions what is missing.
#
# NOTE: This is a SERVICE/STARTUP script, intentionally NOT part of the Cloud
# Agent update script (which only refreshes dependencies). Run it manually after
# `npm install` when you need the app to actually talk to a database.
#
# Requires: docker, supabase CLI, node deps installed (npm install).

set -uo pipefail
cd "$(dirname "$0")/.."

TEST_EMAIL="${DEV_TEST_EMAIL:-admin@jadegold.local}"
TEST_PASSWORD="${DEV_TEST_PASSWORD:-Password123!}"
ORG_SLUG="jade-gold-nyc"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

# 1) Ensure the Docker daemon is up (Supabase runs in Docker) -----------------
if ! docker info >/dev/null 2>&1; then
  log "Starting Docker daemon"
  sudo dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 1; done
  sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
fi
docker info >/dev/null 2>&1 || { echo "Docker is not available"; exit 1; }

# 2) Ensure the Supabase stack is running -------------------------------------
# `supabase start` auto-applies migrations, but a fresh apply hits one bad
# statement in 0058 (a REVOKE on a function that is never created) AND applies
# objects as the wrong role. So we start with a BARE database (migrations moved
# aside) and apply them ourselves as `supabase_admin` in step 3.
if ! supabase status >/dev/null 2>&1; then
  log "Starting Supabase (bare, migrations applied manually below)"
  HOLD="$(mktemp -d)"
  # Guarantee migrations are restored even if `supabase start` is interrupted
  # (Ctrl-C / SIGTERM) — otherwise supabase/migrations would be left empty and
  # the worktree would show every migration deleted.
  restore_migrations() {
    mv "$HOLD"/*.sql supabase/migrations/ 2>/dev/null || true
    rmdir "$HOLD" 2>/dev/null || true
  }
  trap 'restore_migrations' EXIT INT TERM
  mv supabase/migrations/*.sql "$HOLD"/ 2>/dev/null || true
  supabase start || true
  restore_migrations
  trap - EXIT INT TERM
fi

DB_CONTAINER="$(docker ps --format '{{.Names}}' | grep -m1 supabase_db)"
[ -n "$DB_CONTAINER" ] || { echo "supabase_db container not found"; exit 1; }
psql_admin() { docker exec -i "$DB_CONTAINER" psql -U supabase_admin -d postgres "$@"; }

# 3) Provision the schema (idempotent) ----------------------------------------
# Applied as the `supabase_admin` superuser so anon/authenticated inherit the
# correct default table/function privileges (the app relies on these; migrations
# never GRANT table DML explicitly). ON_ERROR_STOP=0 tolerates the known no-op
# REVOKE in 0058 and re-runs on an already-provisioned DB.
HAS_ORG="$(psql_admin -tAc "select 1 from public.organizations where slug='${ORG_SLUG}' limit 1" 2>/dev/null || true)"
if [ "$HAS_ORG" != "1" ]; then
  log "Applying migrations as supabase_admin"
  for f in supabase/migrations/*.sql; do
    psql_admin -v ON_ERROR_STOP=0 -f - < "$f" >/dev/null 2>&1 || true
  done
else
  log "Schema already provisioned (seed org present) - skipping migrations"
fi

# 4) Write .env.local from the running stack ----------------------------------
log "Writing .env.local"
eval "$(supabase status -o env 2>/dev/null)"
cat > .env.local <<EOF
# Local dev - Supabase CLI stack (generated by scripts/dev-supabase-setup.sh)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

# 5) Create a confirmed test user that owns the seeded org --------------------
HAS_MEMBER="$(psql_admin -tAc "select 1 from public.organization_members m join auth.users u on u.id=m.user_id where u.email='${TEST_EMAIL}' limit 1" 2>/dev/null || true)"
if [ "$HAS_MEMBER" != "1" ]; then
  log "Creating test user ${TEST_EMAIL} and granting org ownership"
  # Best effort: a 422 ("email exists") is fine and handled by the assert below;
  # we do NOT trust this response, we assert the user exists before continuing.
  curl -sS -X POST "${API_URL}/auth/v1/admin/users" \
    -H "apikey: ${SERVICE_ROLE_KEY}" -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${TEST_EMAIL}\",\"password\":\"${TEST_PASSWORD}\",\"email_confirm\":true,\"user_metadata\":{\"full_name\":\"Husam Ari\"}}" \
    >/dev/null 2>&1 || true

  # Assert the user actually exists (Auth API may be unreachable / erroring);
  # never print usable-looking credentials for a user that was not created.
  USER_OK=""
  for _ in $(seq 1 10); do
    USER_OK="$(psql_admin -tAc "select 1 from auth.users where email='${TEST_EMAIL}' limit 1" 2>/dev/null || true)"
    [ "$USER_OK" = "1" ] && break
    sleep 1
  done
  if [ "$USER_OK" != "1" ]; then
    echo "HATA: test kullanıcısı oluşturulamadı (Supabase Auth admin API'ye ulaşılamadı mı?)." >&2
    exit 1
  fi

  psql_admin >/dev/null <<SQL
insert into public.profiles (id, full_name)
  select id, 'Husam Ari' from auth.users where email='${TEST_EMAIL}'
  on conflict (id) do nothing;
insert into public.organization_members (org_id, user_id, role)
  select o.id, u.id, 'owner' from public.organizations o, auth.users u
  where o.slug='${ORG_SLUG}' and u.email='${TEST_EMAIL}'
  on conflict do nothing;
update public.profiles p set active_org_id=o.id
  from public.organizations o where o.slug='${ORG_SLUG}'
  and p.id=(select id from auth.users where email='${TEST_EMAIL}');
SQL
else
  log "Test user already provisioned - skipping"
fi

log "Done. Run 'npm run dev' and log in at http://localhost:3000/login"
echo "    email:    ${TEST_EMAIL}"
echo "    password: ${TEST_PASSWORD}"
echo "    Supabase Studio: ${STUDIO_URL:-http://127.0.0.1:54323}"
