-- 0161_artifact_xmas26_gallery.sql
-- by Artifact Studio Christmas 2026: 10 sales images per listing (positions 0..9 = frames 01..10),
-- image_url = frame 01, num_images = 10, missingHero false, image blocker rewritten. Only unpublished drafts.
-- Panel only; no Etsy write. Images: public/artifact/xmas26/<ID>/01..10.jpg (docs: images.json, qa/).
-- Generator: docs/artifact-studio/xmas26/gen_images_migration.py. DO NOT EDIT BY HAND.
-- Seal (run after apply):
--   select count(*), md5(string_agg(p.sku||'|'||li.position||'|'||li.url||'|'||li.alt, E'\n'
--     order by p.sku||'|'||li.position||'|'||li.url||'|'||li.alt collate "C"))
--   from listing_images li join products p on p.id = li.product_id
--   where p.org_id = '2c254edf-2119-4079-b09e-dc672e32c1f9' and p.sku like 'BAS-XM-%';
--   expected: 300 / d1cd9521550b54edc03695bc9d839de1
begin;

create temporary table _xg(sku text, pos int, url text, alt text) on commit drop;
insert into _xg values
($gl$BAS-XM-R01$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/01.jpg$gl$, $gl$Holly Berry Ring in solid gold on icy silver blue paper$gl$),
($gl$BAS-XM-R01$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/02.jpg$gl$, $gl$Holly Berry Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R01$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/03.jpg$gl$, $gl$Holly Berry Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R01$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/04.jpg$gl$, $gl$Holly Berry Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R01$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/05.jpg$gl$, $gl$Scale view of the Holly Berry Ring, holly top 9 x 7 mm$gl$),
($gl$BAS-XM-R01$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/06.jpg$gl$, $gl$Close-up of the pine green and cranberry red enamel of the Holly Berry Ring$gl$),
($gl$BAS-XM-R01$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/07.jpg$gl$, $gl$Holly Berry Ring in a Christmas still life with fir and pine cones$gl$),
($gl$BAS-XM-R01$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/08.jpg$gl$, $gl$Holly Berry Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R01$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/09.jpg$gl$, $gl$Holly Berry Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R01$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R01/10.jpg$gl$, $gl$Holly Berry Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B01$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/01.jpg$gl$, $gl$Holly Station Bracelet in solid gold on dove grey paper$gl$),
($gl$BAS-XM-B01$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/02.jpg$gl$, $gl$Holly Station Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B01$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/03.jpg$gl$, $gl$Holly Station Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B01$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/04.jpg$gl$, $gl$Holly Station Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B01$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/05.jpg$gl$, $gl$Scale view of the Holly Station Bracelet, three holly stations, each 6 x 5 mm$gl$),
($gl$BAS-XM-B01$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/06.jpg$gl$, $gl$Close-up of the pine green and cranberry red enamel of the Holly Station Bracelet$gl$),
($gl$BAS-XM-B01$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/07.jpg$gl$, $gl$Holly Station Bracelet in a Christmas still life with fir and pine cones$gl$),
($gl$BAS-XM-B01$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/08.jpg$gl$, $gl$Holly Station Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B01$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/09.jpg$gl$, $gl$Holly Station Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B01$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B01/10.jpg$gl$, $gl$Holly Station Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N01$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/01.jpg$gl$, $gl$Holly Sprig Necklace in solid gold on mushroom taupe paper$gl$),
($gl$BAS-XM-N01$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/02.jpg$gl$, $gl$Holly Sprig Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N01$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/03.jpg$gl$, $gl$Holly Sprig Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N01$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/04.jpg$gl$, $gl$Holly Sprig Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N01$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/05.jpg$gl$, $gl$Scale view of the Holly Sprig Necklace, sprig 13 x 10 mm$gl$),
($gl$BAS-XM-N01$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/06.jpg$gl$, $gl$Close-up of the pine green and cranberry red enamel of the Holly Sprig Necklace$gl$),
($gl$BAS-XM-N01$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/07.jpg$gl$, $gl$Holly Sprig Necklace in a Christmas still life with fir and pine cones$gl$),
($gl$BAS-XM-N01$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/08.jpg$gl$, $gl$Holly Sprig Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N01$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/09.jpg$gl$, $gl$Holly Sprig Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N01$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N01/10.jpg$gl$, $gl$Holly Sprig Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R02$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/01.jpg$gl$, $gl$Candy Cane Stripe Ring in solid gold on fir green paper$gl$),
($gl$BAS-XM-R02$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/02.jpg$gl$, $gl$Candy Cane Stripe Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R02$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/03.jpg$gl$, $gl$Candy Cane Stripe Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R02$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/04.jpg$gl$, $gl$Candy Cane Stripe Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R02$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/05.jpg$gl$, $gl$Scale view of the Candy Cane Stripe Ring, band 3 mm wide, stripes about 2 mm$gl$),
($gl$BAS-XM-R02$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/06.jpg$gl$, $gl$Close-up of the cranberry red and snow white enamel of the Candy Cane Stripe Ring$gl$),
($gl$BAS-XM-R02$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/07.jpg$gl$, $gl$Candy Cane Stripe Ring in a Christmas still life with a peppermint candy cane$gl$),
($gl$BAS-XM-R02$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/08.jpg$gl$, $gl$Candy Cane Stripe Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R02$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/09.jpg$gl$, $gl$Candy Cane Stripe Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R02$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R02/10.jpg$gl$, $gl$Candy Cane Stripe Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B02$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/01.jpg$gl$, $gl$Candy Cane Charm Bracelet in solid gold on frosted mint paper$gl$),
($gl$BAS-XM-B02$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/02.jpg$gl$, $gl$Candy Cane Charm Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B02$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/03.jpg$gl$, $gl$Candy Cane Charm Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B02$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/04.jpg$gl$, $gl$Candy Cane Charm Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B02$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/05.jpg$gl$, $gl$Scale view of the Candy Cane Charm Bracelet, candy cane 4 x 10 mm$gl$),
($gl$BAS-XM-B02$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/06.jpg$gl$, $gl$Close-up of the cranberry red and snow white enamel of the Candy Cane Charm Bracelet$gl$),
($gl$BAS-XM-B02$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/07.jpg$gl$, $gl$Candy Cane Charm Bracelet in a Christmas still life with a peppermint candy cane$gl$),
($gl$BAS-XM-B02$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/08.jpg$gl$, $gl$Candy Cane Charm Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B02$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/09.jpg$gl$, $gl$Candy Cane Charm Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B02$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B02/10.jpg$gl$, $gl$Candy Cane Charm Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N02$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/01.jpg$gl$, $gl$Candy Cane Hook Necklace in solid gold on deep forest teal paper$gl$),
($gl$BAS-XM-N02$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/02.jpg$gl$, $gl$Candy Cane Hook Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N02$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/03.jpg$gl$, $gl$Candy Cane Hook Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N02$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/04.jpg$gl$, $gl$Candy Cane Hook Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N02$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/05.jpg$gl$, $gl$Scale view of the Candy Cane Hook Necklace, candy cane 7 x 16 mm$gl$),
($gl$BAS-XM-N02$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/06.jpg$gl$, $gl$Close-up of the cranberry red and snow white enamel of the Candy Cane Hook Necklace$gl$),
($gl$BAS-XM-N02$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/07.jpg$gl$, $gl$Candy Cane Hook Necklace in a Christmas still life with a peppermint candy cane$gl$),
($gl$BAS-XM-N02$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/08.jpg$gl$, $gl$Candy Cane Hook Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N02$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/09.jpg$gl$, $gl$Candy Cane Hook Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N02$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N02/10.jpg$gl$, $gl$Candy Cane Hook Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R03$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/01.jpg$gl$, $gl$Gingerbread Man Ring in solid gold on powder blue paper$gl$),
($gl$BAS-XM-R03$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/02.jpg$gl$, $gl$Gingerbread Man Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R03$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/03.jpg$gl$, $gl$Gingerbread Man Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R03$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/04.jpg$gl$, $gl$Gingerbread Man Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R03$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/05.jpg$gl$, $gl$Scale view of the Gingerbread Man Ring, gingerbread man 7 x 8 mm$gl$),
($gl$BAS-XM-R03$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/06.jpg$gl$, $gl$Close-up of the gingerbread brown enamel of the Gingerbread Man Ring$gl$),
($gl$BAS-XM-R03$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/07.jpg$gl$, $gl$Gingerbread Man Ring in a Christmas still life with a gingerbread cookie$gl$),
($gl$BAS-XM-R03$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/08.jpg$gl$, $gl$Gingerbread Man Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R03$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/09.jpg$gl$, $gl$Gingerbread Man Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R03$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R03/10.jpg$gl$, $gl$Gingerbread Man Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B03$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/01.jpg$gl$, $gl$Gingerbread Heart Bracelet in solid gold on pale periwinkle paper$gl$),
($gl$BAS-XM-B03$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/02.jpg$gl$, $gl$Gingerbread Heart Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B03$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/03.jpg$gl$, $gl$Gingerbread Heart Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B03$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/04.jpg$gl$, $gl$Gingerbread Heart Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B03$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/05.jpg$gl$, $gl$Scale view of the Gingerbread Heart Bracelet, three hearts, each 5 mm$gl$),
($gl$BAS-XM-B03$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/06.jpg$gl$, $gl$Close-up of the gingerbread brown enamel of the Gingerbread Heart Bracelet$gl$),
($gl$BAS-XM-B03$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/07.jpg$gl$, $gl$Gingerbread Heart Bracelet in a Christmas still life with a gingerbread cookie$gl$),
($gl$BAS-XM-B03$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/08.jpg$gl$, $gl$Gingerbread Heart Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B03$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/09.jpg$gl$, $gl$Gingerbread Heart Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B03$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B03/10.jpg$gl$, $gl$Gingerbread Heart Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N03$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/01.jpg$gl$, $gl$Gingerbread Man Necklace in solid gold on Wedgwood blue paper$gl$),
($gl$BAS-XM-N03$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/02.jpg$gl$, $gl$Gingerbread Man Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N03$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/03.jpg$gl$, $gl$Gingerbread Man Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N03$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/04.jpg$gl$, $gl$Gingerbread Man Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N03$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/05.jpg$gl$, $gl$Scale view of the Gingerbread Man Necklace, gingerbread man 11 x 13 mm$gl$),
($gl$BAS-XM-N03$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/06.jpg$gl$, $gl$Close-up of the gingerbread brown enamel of the Gingerbread Man Necklace$gl$),
($gl$BAS-XM-N03$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/07.jpg$gl$, $gl$Gingerbread Man Necklace in a Christmas still life with a gingerbread cookie$gl$),
($gl$BAS-XM-N03$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/08.jpg$gl$, $gl$Gingerbread Man Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N03$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/09.jpg$gl$, $gl$Gingerbread Man Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N03$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N03/10.jpg$gl$, $gl$Gingerbread Man Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R04$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/01.jpg$gl$, $gl$Bauble Ring in solid gold on blush rose paper$gl$),
($gl$BAS-XM-R04$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/02.jpg$gl$, $gl$Bauble Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R04$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/03.jpg$gl$, $gl$Bauble Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R04$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/04.jpg$gl$, $gl$Bauble Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R04$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/05.jpg$gl$, $gl$Scale view of the Bauble Ring, bauble 7 mm with gold cap$gl$),
($gl$BAS-XM-R04$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/06.jpg$gl$, $gl$Close-up of the emerald green enamel of the Bauble Ring$gl$),
($gl$BAS-XM-R04$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/07.jpg$gl$, $gl$Bauble Ring in a Christmas still life with a glass bauble$gl$),
($gl$BAS-XM-R04$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/08.jpg$gl$, $gl$Bauble Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R04$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/09.jpg$gl$, $gl$Bauble Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R04$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R04/10.jpg$gl$, $gl$Bauble Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B04$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/01.jpg$gl$, $gl$Bauble Trio Bracelet in solid gold on dusty pink paper$gl$),
($gl$BAS-XM-B04$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/02.jpg$gl$, $gl$Bauble Trio Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B04$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/03.jpg$gl$, $gl$Bauble Trio Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B04$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/04.jpg$gl$, $gl$Bauble Trio Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B04$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/05.jpg$gl$, $gl$Scale view of the Bauble Trio Bracelet, three baubles, each 5 mm$gl$),
($gl$BAS-XM-B04$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/06.jpg$gl$, $gl$Close-up of the emerald green and cranberry red enamel of the Bauble Trio Bracelet$gl$),
($gl$BAS-XM-B04$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/07.jpg$gl$, $gl$Bauble Trio Bracelet in a Christmas still life with a glass bauble$gl$),
($gl$BAS-XM-B04$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/08.jpg$gl$, $gl$Bauble Trio Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B04$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/09.jpg$gl$, $gl$Bauble Trio Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B04$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B04/10.jpg$gl$, $gl$Bauble Trio Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N04$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/01.jpg$gl$, $gl$Bauble Ornament Necklace in solid gold on deep burgundy paper$gl$),
($gl$BAS-XM-N04$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/02.jpg$gl$, $gl$Bauble Ornament Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N04$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/03.jpg$gl$, $gl$Bauble Ornament Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N04$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/04.jpg$gl$, $gl$Bauble Ornament Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N04$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/05.jpg$gl$, $gl$Scale view of the Bauble Ornament Necklace, bauble 10 mm with gold cap$gl$),
($gl$BAS-XM-N04$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/06.jpg$gl$, $gl$Close-up of the emerald green enamel of the Bauble Ornament Necklace$gl$),
($gl$BAS-XM-N04$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/07.jpg$gl$, $gl$Bauble Ornament Necklace in a Christmas still life with a glass bauble$gl$),
($gl$BAS-XM-N04$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/08.jpg$gl$, $gl$Bauble Ornament Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N04$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/09.jpg$gl$, $gl$Bauble Ornament Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N04$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N04/10.jpg$gl$, $gl$Bauble Ornament Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R05$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/01.jpg$gl$, $gl$Snowflake Ring in solid gold on midnight navy paper$gl$),
($gl$BAS-XM-R05$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/02.jpg$gl$, $gl$Snowflake Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R05$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/03.jpg$gl$, $gl$Snowflake Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R05$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/04.jpg$gl$, $gl$Snowflake Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R05$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/05.jpg$gl$, $gl$Scale view of the Snowflake Ring, snowflake 9 mm$gl$),
($gl$BAS-XM-R05$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/06.jpg$gl$, $gl$Close-up of the polished sculpted gold of the Snowflake Ring$gl$),
($gl$BAS-XM-R05$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/07.jpg$gl$, $gl$Snowflake Ring in a Christmas still life with snow and fir$gl$),
($gl$BAS-XM-R05$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/08.jpg$gl$, $gl$Snowflake Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R05$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/09.jpg$gl$, $gl$Snowflake Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R05$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R05/10.jpg$gl$, $gl$Snowflake Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B05$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/01.jpg$gl$, $gl$Snowflake Station Bracelet in solid gold on deep ice teal paper$gl$),
($gl$BAS-XM-B05$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/02.jpg$gl$, $gl$Snowflake Station Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B05$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/03.jpg$gl$, $gl$Snowflake Station Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B05$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/04.jpg$gl$, $gl$Snowflake Station Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B05$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/05.jpg$gl$, $gl$Scale view of the Snowflake Station Bracelet, three snowflakes, each 6 mm$gl$),
($gl$BAS-XM-B05$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/06.jpg$gl$, $gl$Close-up of the polished sculpted gold of the Snowflake Station Bracelet$gl$),
($gl$BAS-XM-B05$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/07.jpg$gl$, $gl$Snowflake Station Bracelet in a Christmas still life with snow and fir$gl$),
($gl$BAS-XM-B05$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/08.jpg$gl$, $gl$Snowflake Station Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B05$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/09.jpg$gl$, $gl$Snowflake Station Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B05$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B05/10.jpg$gl$, $gl$Snowflake Station Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N05$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/01.jpg$gl$, $gl$Snowflake Pendant Necklace in solid gold on charcoal blue paper$gl$),
($gl$BAS-XM-N05$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/02.jpg$gl$, $gl$Snowflake Pendant Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N05$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/03.jpg$gl$, $gl$Snowflake Pendant Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N05$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/04.jpg$gl$, $gl$Snowflake Pendant Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N05$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/05.jpg$gl$, $gl$Scale view of the Snowflake Pendant Necklace, snowflake 14 mm$gl$),
($gl$BAS-XM-N05$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/06.jpg$gl$, $gl$Close-up of the polished sculpted gold of the Snowflake Pendant Necklace$gl$),
($gl$BAS-XM-N05$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/07.jpg$gl$, $gl$Snowflake Pendant Necklace in a Christmas still life with snow and fir$gl$),
($gl$BAS-XM-N05$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/08.jpg$gl$, $gl$Snowflake Pendant Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N05$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/09.jpg$gl$, $gl$Snowflake Pendant Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N05$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N05/10.jpg$gl$, $gl$Snowflake Pendant Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R06$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/01.jpg$gl$, $gl$Christmas Tree Ring in solid gold on deep cranberry paper$gl$),
($gl$BAS-XM-R06$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/02.jpg$gl$, $gl$Christmas Tree Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R06$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/03.jpg$gl$, $gl$Christmas Tree Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R06$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/04.jpg$gl$, $gl$Christmas Tree Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R06$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/05.jpg$gl$, $gl$Scale view of the Christmas Tree Ring, tree 6 x 9 mm$gl$),
($gl$BAS-XM-R06$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/06.jpg$gl$, $gl$Close-up of the pine green enamel of the Christmas Tree Ring$gl$),
($gl$BAS-XM-R06$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/07.jpg$gl$, $gl$Christmas Tree Ring in a Christmas still life with fir and cinnamon$gl$),
($gl$BAS-XM-R06$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/08.jpg$gl$, $gl$Christmas Tree Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R06$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/09.jpg$gl$, $gl$Christmas Tree Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R06$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R06/10.jpg$gl$, $gl$Christmas Tree Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B06$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/01.jpg$gl$, $gl$Tree Line Bracelet in solid gold on rose pink paper$gl$),
($gl$BAS-XM-B06$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/02.jpg$gl$, $gl$Tree Line Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B06$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/03.jpg$gl$, $gl$Tree Line Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B06$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/04.jpg$gl$, $gl$Tree Line Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B06$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/05.jpg$gl$, $gl$Scale view of the Tree Line Bracelet, three trees, 4 x 6, 5 x 7 and 4 x 6 mm$gl$),
($gl$BAS-XM-B06$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/06.jpg$gl$, $gl$Close-up of the pine green enamel of the Tree Line Bracelet$gl$),
($gl$BAS-XM-B06$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/07.jpg$gl$, $gl$Tree Line Bracelet in a Christmas still life with fir and cinnamon$gl$),
($gl$BAS-XM-B06$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/08.jpg$gl$, $gl$Tree Line Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B06$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/09.jpg$gl$, $gl$Tree Line Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B06$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B06/10.jpg$gl$, $gl$Tree Line Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N06$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/01.jpg$gl$, $gl$Christmas Tree Necklace in solid gold on mulled wine plum paper$gl$),
($gl$BAS-XM-N06$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/02.jpg$gl$, $gl$Christmas Tree Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N06$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/03.jpg$gl$, $gl$Christmas Tree Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N06$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/04.jpg$gl$, $gl$Christmas Tree Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N06$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/05.jpg$gl$, $gl$Scale view of the Christmas Tree Necklace, tree 10 x 15 mm$gl$),
($gl$BAS-XM-N06$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/06.jpg$gl$, $gl$Close-up of the pine green enamel of the Christmas Tree Necklace$gl$),
($gl$BAS-XM-N06$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/07.jpg$gl$, $gl$Christmas Tree Necklace in a Christmas still life with fir and cinnamon$gl$),
($gl$BAS-XM-N06$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/08.jpg$gl$, $gl$Christmas Tree Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N06$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/09.jpg$gl$, $gl$Christmas Tree Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N06$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N06/10.jpg$gl$, $gl$Christmas Tree Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R07$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/01.jpg$gl$, $gl$Mistletoe Bypass Ring in solid gold on dusty mauve paper$gl$),
($gl$BAS-XM-R07$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/02.jpg$gl$, $gl$Mistletoe Bypass Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R07$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/03.jpg$gl$, $gl$Mistletoe Bypass Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R07$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/04.jpg$gl$, $gl$Mistletoe Bypass Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R07$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/05.jpg$gl$, $gl$Scale view of the Mistletoe Bypass Ring, leaves 6 mm, berries 2 mm, open ring$gl$),
($gl$BAS-XM-R07$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/06.jpg$gl$, $gl$Close-up of the mistletoe sage and snow white enamel of the Mistletoe Bypass Ring$gl$),
($gl$BAS-XM-R07$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/07.jpg$gl$, $gl$Mistletoe Bypass Ring in a Christmas still life with a mistletoe sprig$gl$),
($gl$BAS-XM-R07$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/08.jpg$gl$, $gl$Mistletoe Bypass Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R07$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/09.jpg$gl$, $gl$Mistletoe Bypass Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R07$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R07/10.jpg$gl$, $gl$Mistletoe Bypass Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B07$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/01.jpg$gl$, $gl$Mistletoe Sprig Bracelet in solid gold on deep plum paper$gl$),
($gl$BAS-XM-B07$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/02.jpg$gl$, $gl$Mistletoe Sprig Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B07$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/03.jpg$gl$, $gl$Mistletoe Sprig Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B07$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/04.jpg$gl$, $gl$Mistletoe Sprig Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B07$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/05.jpg$gl$, $gl$Scale view of the Mistletoe Sprig Bracelet, sprig 10 x 6 mm$gl$),
($gl$BAS-XM-B07$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/06.jpg$gl$, $gl$Close-up of the mistletoe sage and snow white enamel of the Mistletoe Sprig Bracelet$gl$),
($gl$BAS-XM-B07$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/07.jpg$gl$, $gl$Mistletoe Sprig Bracelet in a Christmas still life with a mistletoe sprig$gl$),
($gl$BAS-XM-B07$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/08.jpg$gl$, $gl$Mistletoe Sprig Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B07$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/09.jpg$gl$, $gl$Mistletoe Sprig Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B07$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B07/10.jpg$gl$, $gl$Mistletoe Sprig Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N07$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/01.jpg$gl$, $gl$Mistletoe Drop Necklace in solid gold on rosewood paper$gl$),
($gl$BAS-XM-N07$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/02.jpg$gl$, $gl$Mistletoe Drop Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N07$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/03.jpg$gl$, $gl$Mistletoe Drop Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N07$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/04.jpg$gl$, $gl$Mistletoe Drop Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N07$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/05.jpg$gl$, $gl$Scale view of the Mistletoe Drop Necklace, sprig 9 x 14 mm$gl$),
($gl$BAS-XM-N07$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/06.jpg$gl$, $gl$Close-up of the mistletoe sage and snow white enamel of the Mistletoe Drop Necklace$gl$),
($gl$BAS-XM-N07$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/07.jpg$gl$, $gl$Mistletoe Drop Necklace in a Christmas still life with a mistletoe sprig$gl$),
($gl$BAS-XM-N07$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/08.jpg$gl$, $gl$Mistletoe Drop Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N07$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/09.jpg$gl$, $gl$Mistletoe Drop Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N07$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N07/10.jpg$gl$, $gl$Mistletoe Drop Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R08$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/01.jpg$gl$, $gl$Bell Ring in solid gold on deep emerald paper$gl$),
($gl$BAS-XM-R08$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/02.jpg$gl$, $gl$Bell Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R08$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/03.jpg$gl$, $gl$Bell Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R08$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/04.jpg$gl$, $gl$Bell Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R08$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/05.jpg$gl$, $gl$Scale view of the Bell Ring, bell 6 x 7 mm$gl$),
($gl$BAS-XM-R08$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/06.jpg$gl$, $gl$Close-up of the polished sculpted gold of the Bell Ring$gl$),
($gl$BAS-XM-R08$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/07.jpg$gl$, $gl$Bell Ring in a Christmas still life with a velvet bow$gl$),
($gl$BAS-XM-R08$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/08.jpg$gl$, $gl$Bell Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R08$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/09.jpg$gl$, $gl$Bell Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R08$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R08/10.jpg$gl$, $gl$Bell Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B08$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/01.jpg$gl$, $gl$Twin Bell Bracelet in solid gold on oxblood paper$gl$),
($gl$BAS-XM-B08$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/02.jpg$gl$, $gl$Twin Bell Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B08$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/03.jpg$gl$, $gl$Twin Bell Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B08$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/04.jpg$gl$, $gl$Twin Bell Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B08$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/05.jpg$gl$, $gl$Scale view of the Twin Bell Bracelet, two bells, each 5 x 6 mm$gl$),
($gl$BAS-XM-B08$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/06.jpg$gl$, $gl$Close-up of the polished sculpted gold of the Twin Bell Bracelet$gl$),
($gl$BAS-XM-B08$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/07.jpg$gl$, $gl$Twin Bell Bracelet in a Christmas still life with a velvet bow$gl$),
($gl$BAS-XM-B08$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/08.jpg$gl$, $gl$Twin Bell Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B08$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/09.jpg$gl$, $gl$Twin Bell Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B08$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B08/10.jpg$gl$, $gl$Twin Bell Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N08$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/01.jpg$gl$, $gl$Bell Pendant Necklace in solid gold on deep spruce paper$gl$),
($gl$BAS-XM-N08$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/02.jpg$gl$, $gl$Bell Pendant Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N08$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/03.jpg$gl$, $gl$Bell Pendant Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N08$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/04.jpg$gl$, $gl$Bell Pendant Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N08$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/05.jpg$gl$, $gl$Scale view of the Bell Pendant Necklace, bell 10 x 12 mm$gl$),
($gl$BAS-XM-N08$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/06.jpg$gl$, $gl$Close-up of the polished sculpted gold of the Bell Pendant Necklace$gl$),
($gl$BAS-XM-N08$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/07.jpg$gl$, $gl$Bell Pendant Necklace in a Christmas still life with a velvet bow$gl$),
($gl$BAS-XM-N08$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/08.jpg$gl$, $gl$Bell Pendant Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N08$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/09.jpg$gl$, $gl$Bell Pendant Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N08$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N08/10.jpg$gl$, $gl$Bell Pendant Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R09$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/01.jpg$gl$, $gl$Poinsettia Ring in solid gold on pine green paper$gl$),
($gl$BAS-XM-R09$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/02.jpg$gl$, $gl$Poinsettia Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R09$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/03.jpg$gl$, $gl$Poinsettia Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R09$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/04.jpg$gl$, $gl$Poinsettia Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R09$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/05.jpg$gl$, $gl$Scale view of the Poinsettia Ring, flower 9 mm$gl$),
($gl$BAS-XM-R09$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/06.jpg$gl$, $gl$Close-up of the poinsettia red enamel of the Poinsettia Ring$gl$),
($gl$BAS-XM-R09$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/07.jpg$gl$, $gl$Poinsettia Ring in a Christmas still life with fir and cranberries$gl$),
($gl$BAS-XM-R09$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/08.jpg$gl$, $gl$Poinsettia Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R09$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/09.jpg$gl$, $gl$Poinsettia Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R09$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R09/10.jpg$gl$, $gl$Poinsettia Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B09$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/01.jpg$gl$, $gl$Poinsettia Station Bracelet in solid gold on eucalyptus paper$gl$),
($gl$BAS-XM-B09$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/02.jpg$gl$, $gl$Poinsettia Station Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B09$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/03.jpg$gl$, $gl$Poinsettia Station Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B09$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/04.jpg$gl$, $gl$Poinsettia Station Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B09$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/05.jpg$gl$, $gl$Scale view of the Poinsettia Station Bracelet, three flowers, each 6 mm$gl$),
($gl$BAS-XM-B09$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/06.jpg$gl$, $gl$Close-up of the poinsettia red enamel of the Poinsettia Station Bracelet$gl$),
($gl$BAS-XM-B09$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/07.jpg$gl$, $gl$Poinsettia Station Bracelet in a Christmas still life with fir and cranberries$gl$),
($gl$BAS-XM-B09$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/08.jpg$gl$, $gl$Poinsettia Station Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B09$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/09.jpg$gl$, $gl$Poinsettia Station Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B09$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B09/10.jpg$gl$, $gl$Poinsettia Station Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N09$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/01.jpg$gl$, $gl$Poinsettia Necklace in solid gold on deep teal paper$gl$),
($gl$BAS-XM-N09$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/02.jpg$gl$, $gl$Poinsettia Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N09$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/03.jpg$gl$, $gl$Poinsettia Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N09$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/04.jpg$gl$, $gl$Poinsettia Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N09$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/05.jpg$gl$, $gl$Scale view of the Poinsettia Necklace, flower 13 mm$gl$),
($gl$BAS-XM-N09$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/06.jpg$gl$, $gl$Close-up of the poinsettia red enamel of the Poinsettia Necklace$gl$),
($gl$BAS-XM-N09$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/07.jpg$gl$, $gl$Poinsettia Necklace in a Christmas still life with fir and cranberries$gl$),
($gl$BAS-XM-N09$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/08.jpg$gl$, $gl$Poinsettia Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N09$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/09.jpg$gl$, $gl$Poinsettia Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N09$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N09/10.jpg$gl$, $gl$Poinsettia Necklace worn with an open wool coat$gl$),
($gl$BAS-XM-R10$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/01.jpg$gl$, $gl$Stocking Ring in solid gold on sage green paper$gl$),
($gl$BAS-XM-R10$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/02.jpg$gl$, $gl$Stocking Ring worn on the hand with a cable-knit sweater$gl$),
($gl$BAS-XM-R10$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/03.jpg$gl$, $gl$Stocking Ring on a hand resting on a wrapped Christmas gift$gl$),
($gl$BAS-XM-R10$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/04.jpg$gl$, $gl$Stocking Ring on a hand rising from a studio plinth$gl$),
($gl$BAS-XM-R10$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/05.jpg$gl$, $gl$Scale view of the Stocking Ring, stocking 6 x 8 mm$gl$),
($gl$BAS-XM-R10$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/06.jpg$gl$, $gl$Close-up of the cranberry red and snow white enamel of the Stocking Ring$gl$),
($gl$BAS-XM-R10$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/07.jpg$gl$, $gl$Stocking Ring in a Christmas still life with a knit mitten and cinnamon$gl$),
($gl$BAS-XM-R10$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/08.jpg$gl$, $gl$Stocking Ring on a white card beside an open gift box$gl$),
($gl$BAS-XM-R10$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/09.jpg$gl$, $gl$Stocking Ring shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-R10$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/R10/10.jpg$gl$, $gl$Stocking Ring worn with a velvet blazer$gl$),
($gl$BAS-XM-B10$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/01.jpg$gl$, $gl$Stocking Charm Bracelet in solid gold on Nordic blue grey paper$gl$),
($gl$BAS-XM-B10$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/02.jpg$gl$, $gl$Stocking Charm Bracelet worn on the wrist with a cable-knit sweater$gl$),
($gl$BAS-XM-B10$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/03.jpg$gl$, $gl$Stocking Charm Bracelet on the wrist while tying a gift ribbon$gl$),
($gl$BAS-XM-B10$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/04.jpg$gl$, $gl$Stocking Charm Bracelet on a wrist rising from a studio plinth$gl$),
($gl$BAS-XM-B10$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/05.jpg$gl$, $gl$Scale view of the Stocking Charm Bracelet, stocking 5 x 7 mm$gl$),
($gl$BAS-XM-B10$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/06.jpg$gl$, $gl$Close-up of the cranberry red and snow white enamel of the Stocking Charm Bracelet$gl$),
($gl$BAS-XM-B10$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/07.jpg$gl$, $gl$Stocking Charm Bracelet in a Christmas still life with a knit mitten and cinnamon$gl$),
($gl$BAS-XM-B10$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/08.jpg$gl$, $gl$Stocking Charm Bracelet on a white card beside an open gift box$gl$),
($gl$BAS-XM-B10$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/09.jpg$gl$, $gl$Stocking Charm Bracelet shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-B10$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/B10/10.jpg$gl$, $gl$Stocking Charm Bracelet worn with a velvet blazer$gl$),
($gl$BAS-XM-N10$gl$, 0, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/01.jpg$gl$, $gl$Stocking Necklace in solid gold on fir needle green paper$gl$),
($gl$BAS-XM-N10$gl$, 1, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/02.jpg$gl$, $gl$Stocking Necklace worn at the collarbone with a cable-knit sweater$gl$),
($gl$BAS-XM-N10$gl$, 2, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/03.jpg$gl$, $gl$Stocking Necklace worn with a velvet neckline$gl$),
($gl$BAS-XM-N10$gl$, 3, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/04.jpg$gl$, $gl$Stocking Necklace seen in profile at the neck$gl$),
($gl$BAS-XM-N10$gl$, 4, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/05.jpg$gl$, $gl$Scale view of the Stocking Necklace, stocking 9 x 13 mm$gl$),
($gl$BAS-XM-N10$gl$, 5, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/06.jpg$gl$, $gl$Close-up of the cranberry red and snow white enamel of the Stocking Necklace$gl$),
($gl$BAS-XM-N10$gl$, 6, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/07.jpg$gl$, $gl$Stocking Necklace in a Christmas still life with a knit mitten and cinnamon$gl$),
($gl$BAS-XM-N10$gl$, 7, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/08.jpg$gl$, $gl$Stocking Necklace on a white card beside an open gift box$gl$),
($gl$BAS-XM-N10$gl$, 8, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/09.jpg$gl$, $gl$Stocking Necklace shown in yellow, white and rose gold (colour visualization)$gl$),
($gl$BAS-XM-N10$gl$, 9, $gl$https://amuletta.artifactstudio.info/artifact/xmas26/N10/10.jpg$gl$, $gl$Stocking Necklace worn with an open wool coat$gl$);

insert into public.listing_images (org_id, product_id, url, source, alt, position)
select p.org_id, p.id, g.url, 'url', g.alt, g.pos
from _xg g
join public.products p on p.org_id = '2c254edf-2119-4079-b09e-dc672e32c1f9' and p.sku = g.sku and p.etsy_listing_id is null
where not exists (select 1 from public.listing_images li where li.product_id = p.id and li.url = g.url);

update public.products p
set image_url = g.url, num_images = 10,
    listing_metadata = jsonb_set(jsonb_set(p.listing_metadata, '{missingHero}', 'false'::jsonb),
      '{approval,blockers,2}', to_jsonb($gl$Images are design visualizations (Higgsfield): 10 sales frames per listing in its colour world, frame 09 is a metal colour visualization; photograph the physical piece before or after the first sale.$gl$::text))
from _xg g
where g.sku = p.sku and g.pos = 0 and p.org_id = '2c254edf-2119-4079-b09e-dc672e32c1f9' and p.etsy_listing_id is null;

commit;
